import type { Lesson } from "./lesson-types";

export const lessonsEn: Lesson[] = [
  {
    slug: "why-you-finish-fast",
    title: "Why you finish fast",
    minutes: 3,
    unlockDay: 0,
    body: [
      "Ejaculation is a reflex. Like every reflex, it has a threshold — a level of arousal past which the body takes over and the decision is no longer yours. Finishing fast is not a character flaw and it is almost never a failure of willpower. It means your threshold sits lower than you want it, or that you cannot feel yourself approaching it.",
      "Three things push that threshold down, and most men have some combination of all three. The first is conditioning: years of rushing teach the nervous system a fast route from arousal to finish, and nervous systems are extremely good at learning whatever you repeat. The second is anxiety: monitoring yourself raises arousal, which brings the finish closer, which confirms the fear — a loop that tightens every time it runs. The third is the physical base: poor sleep, no movement, and ongoing gut trouble leave you with a nervous system that is already reactive before anything begins.",
      "Notice what is not on that list. Penis size, testosterone in most cases, and moral failure. Also not on the list: needing a stronger pill.",
      "Every one of those three causes responds to training rather than to chemistry. That is the entire premise of this programme, and it is why we begin by measuring — so that in twelve days you are looking at evidence instead of at somebody's promise.",
    ],
  },
  {
    slug: "how-to-measure",
    title: "How to measure",
    minutes: 3,
    unlockDay: 1,
    body: [
      "Four steps. That is the whole thing.",
      "1. Open Measure and tick the 4 checks.",
      "2. Hit START the moment you begin.",
      "3. Do it normally. Do NOT try to last. Do not stop and start. Do not use the technique.",
      "4. Hit STOP the moment you finish. The app keeps the number.",
      "Most men do this on their own. That is normal and that is what we expect — you do not need a partner and you do not need anyone holding a stopwatch. If you would rather not touch your phone in the moment, note the time on your clock and type it in afterwards. There is a button for that.",
      "Now the four checks, and why each one is there.",
      "2 days since you last came. This is the one men get wrong most. Three days of build-up before Day 12 against two hours before Day 1 will give you a shorter Day 12 and a false conclusion. Same gap both times.",
      "No alcohol today. It changes your result and it changes it differently every time.",
      "No training session since yesterday. A session the same day leaves you dulled.",
      "Same method both times. Whatever you pick on Day 1 — app timer or your own clock — use the same one on Day 12.",
      "One more rule: whatever you do on Day 1, do the same on Day 12. On your own both times, or with a partner both times. Never one of each. Those are two different measurements and comparing them tells you nothing.",
      "Last thing, and it is honest. Timing yourself is pressure, and pressure makes men finish faster. Your Day 1 number will probably be lower than a normal night. That does not matter at all — as long as Day 12 carries the same pressure, the comparison holds. That is the whole point of keeping it identical.",
    ],
  },
  {
    slug: "the-6-10-method",
    title: "The 6/10 Method",
    minutes: 5,
    unlockDay: 2,
    body: [
      "Ask a man who finishes in two minutes what number he was on thirty seconds earlier. He cannot tell you. That is the whole problem — the end arrives with no warning because nothing was being watched on the way up.",
      "So here is the scale, with what each one actually feels like. Learn these, not the numbers.",
      "1 to 4 — Turned on, but nothing is building. Breathing normal. You could stop and hold a conversation.",
      "5 — Fully hard and comfortable. No tightness anywhere. Nothing pulling.",
      "6 — THIS IS YOUR STOP. Four signs, and you only need one of them: your breathing gets shorter without you deciding to; a small tightening underneath, behind the balls; it starts to feel like it is moving on its own; you feel the first pull at the base.",
      "7 — A clear building or pulling at the base. Stomach or thighs start to tighten. You have to concentrate to stay level. Already too high.",
      "8 — You are working to hold it. Toes curl, breath held, whole body tight.",
      "9 — The 'I'm about to' feeling. Too late. It is happening whether you like it or not.",
      "How to use it: from the second you start, count in your head. Three. Four. Five. The moment you feel ANY ONE of the four signs at 6, stop. Hands off. Do not wait until you are sure — if you are sure, you are already at 7.",
      "Then wait. From 6 that is usually 60 to 90 seconds. From 7 it is closer to 2 minutes. Do not watch the clock. Go again only when the pulling feeling has completely gone.",
      "You train at 6 and 7. You never go to 9 on purpose. Men always want to argue with this because holding on at the edge feels braver. It is not. At 9 you will clamp down to survive it, and clamping down is the exact tension that makes men finish fast in the first place. You would be practising the problem.",
      "Stopping at 6 teaches you to drive. Stopping at 9 teaches you to panic with better timing.",
      "One last thing. Most men have never noticed 6 in their lives. If your first session ends with you going straight past it, that is not failure — that is the finding. Your first two sessions are only about locating 6. Lasting comes after.",
    ],
  },
  {
    slug: "pelvic-floor",
    title: "The pelvic floor: contract and release",
    minutes: 4,
    unlockDay: 3,
    body: [
      "Almost every article written about this tells men to do kegels, and almost every one of them describes only half the exercise. The squeeze is the half everyone knows. The release is the half that governs control.",
      "Here is the part that matters and that most men have never been told: a meaningful share of premature ejaculation is caused by a pelvic floor that is too tight, not too weak. For those men, more squeezing makes it worse. If you have pelvic aching, discomfort after sitting for long stretches, or a permanent clenched feeling down there, you are probably one of them.",
      "The test is simple. Do ten contractions and pay attention to the release. If letting go feels vague, incomplete, or like the muscle stays half-on, tension is your issue rather than strength.",
      "Standard protocol: three sets of ten, twice daily. Contract five seconds, release five seconds, and never let the release be shorter than the contraction. Breathe throughout — most men hold their breath, which recruits exactly the wrong muscles.",
      "Release-only variation, for the men described above: skip the contractions entirely. Do reverse kegels — a gentle downward and outward push on each exhale — plus slow belly breathing, twice a day. Come back to contractions after two weeks, once letting go feels complete.",
      "And do not walk around clenched all day. You are training a muscle to obey you, not to stand permanently to attention.",
    ],
  },
  {
    slug: "breathing",
    title: "Breathing and the nervous system",
    minutes: 3,
    unlockDay: 4,
    body: [
      "Breathing sounds like the soft part of the programme. It is the part with the most direct physical mechanism.",
      "Ejaculation is driven by the sympathetic nervous system — the same branch that runs fight-or-flight. Anything that raises sympathetic tone brings the threshold closer: stress, adrenaline, shallow rapid breathing, a braced body. Anything that lowers it buys you room.",
      "A long exhale is the fastest lever available. When you breathe out slowly, the parasympathetic branch is engaged directly, heart rate drops within a few beats and muscle tension follows. In at four through the nose, out at six through the mouth. It works in seconds and requires nothing.",
      "This is why every session starts with two minutes of it, and why you exhale long during every stop. You are not calming down as a mood. You are lowering the level your nervous system starts from, so that the same stimulation lands lower on the scale.",
      "Watch your breathing during sex once and you will see the problem: it goes shallow, high in the chest, and often stops entirely near the end. That pattern accelerates everything. Deliberately breathing low and slow is the single easiest change you can make tonight.",
    ],
  },
  {
    slug: "why-pills-fail",
    title: "Why pills make it worse",
    minutes: 4,
    unlockDay: 5,
    body: [
      "This is not a moral argument. It is a mechanical one.",
      "Here is the part that gets missed. Every good night you have with a pill teaches you one thing: that you need the pill. And being afraid you cannot do it without help is itself one of the direct causes of finishing fast. So you end up with the original problem, plus a new fear on top of it. The pill fixes tonight and makes next month harder.",
      "Delay sprays have a second and subtler cost. They reduce sensation, which sounds helpful and is not: your ability to feel where you are on the scale is the exact skill you need. Numbing yourself makes you worse at reading yourself, so when the spray runs out you are not back at the start, you are slightly behind it.",
      "Alcohol trades one hour of lowered anxiety for degraded erection quality, degraded sleep and degraded recovery. It is a bad exchange every single time, and it corrupts any measurement you take.",
      "Then there is the category sold as natural. Health regulators around the world have repeatedly found undeclared pharmaceutical drugs — the same compounds as prescription pills — inside supplements marketed as herbal. If you have been taking those, you may already have been taking the drug you thought you were avoiding, at an unknown dose, with no label and no way to know what else was in the capsule.",
      "One important exception. If a doctor has prescribed you something, do not stop it on your own. Talk to whoever prescribed it. This programme sits alongside medical care; it does not replace it.",
    ],
  },
  {
    slug: "sleep-and-food",
    title: "Sleep, food and erection quality",
    minutes: 3,
    unlockDay: 6,
    body: [
      "Men will do difficult, uncomfortable training for weeks and refuse to go to bed an hour earlier. Sleep is the highest-leverage item in this entire programme and it is free.",
      "Most testosterone release happens during sleep, and short or broken nights measurably reduce it. Sleep also determines how reactive your nervous system is the next day — an under-slept body sits closer to fight-or-flight before anything has even happened, which means every stimulation lands higher on your scale.",
      "Morning erections are the cheapest diagnostic you have. They track sleep quality, circulation and hormonal state, and when men in this programme start improving, those usually move first — often within the first week, well before the clock does. Watch them.",
      "Food matters in a simpler way than most content suggests. You are not on a diet and you are not cutting anything. Three real meals with protein, carbohydrate, vegetables and fat, eaten at roughly the same times each day, with the last one early enough that you are not going to bed full. That is the entire instruction.",
      "The reason we insist on the early dinner and the pre-bed snack is sleep, not digestion. Going to bed stuffed disrupts sleep; going to bed hungry wakes you at three in the morning. The banana and tigernuts sit in the gap between those two failures.",
    ],
  },
  {
    slug: "the-stomach-connection",
    title: "The stomach connection",
    minutes: 3,
    unlockDay: 7,
    body: [
      "This is the part of the programme men find strangest, and for a meaningful minority it turns out to be the whole bottleneck.",
      "If your stomach hurts most days — burning, reflux, bloating, nausea, appetite that comes and goes — that is not a separate problem sitting next to this one. It is upstream of it. Persistent gastric trouble wrecks sleep, suppresses appetite, drains energy and keeps the body in a low-grade stress state. Every one of those pushes your threshold down.",
      "Trying to train ejaculatory control while your gut is inflamed is like tuning an engine with a fuel leak. The tuning is not wrong. It is just being undone faster than you can do it.",
      "So we track stomach comfort alongside everything else, every night, for the whole programme. If the foundation settles it — and regular meals, less alcohol and better sleep often do — you will see it in the log within two weeks.",
      "If it does not settle, that is a conversation for a doctor rather than another protocol. Persistent reflux, burning or bloating deserves proper assessment; depending on your symptoms and history that can include checking for H. pylori, ulcers or reflux disease. Ignoring it and buying a stronger supplement is the expensive route to the same place.",
    ],
  },
  {
    slug: "not-a-habit",
    title: "This is a drill, not a habit",
    minutes: 2,
    unlockDay: 9,
    body: [
      "There is a real risk in a programme like this, and it would be dishonest not to name it: an exercise done alone, several times a week, at scheduled times, can quietly stop being training and start being a habit.",
      "The structure is deliberately designed against that. Sessions are prescribed rather than done on impulse. They are capped in length. They happen at planned times. Nothing happens outside them. If you have a partner, sex replaces a session rather than being added to one. And there are rest days built in, which are not optional.",
      "The no-screens rule belongs here too. Screens are not banned for moral reasons — they are banned because high-intensity visual stimulation reinforces the exact conditioning you are spending twelve days overwriting.",
      "Two signals to watch for. If you find yourself looking forward to the session more than to sex with your partner, stop and message us. If you are doing extra sessions outside the plan, stop and message us. Neither means you have done something wrong; both mean the plan needs adjusting to you.",
      "The goal is to retire this drill. By the end of the 30-Day Sprint the work has moved into partnered sex, which is where it was always meant to end up. Scaffolding comes down once the building stands.",
    ],
  },
  {
    slug: "reading-your-result",
    title: "How to read your result",
    minutes: 4,
    unlockDay: 12,
    body: [
      "There are four ways this can go and three of them are good news.",
      "The number moved and the markers rose. The clearest outcome. The mechanism is working on you and dose is your remaining variable — more of the same, loaded heavier, then moved into partnered sex.",
      "The markers rose but the clock barely moved. This is the most common result at twelve days and it is not a failure. Energy, sleep, morning erections and your own sense of control shift before the reflex does, because a reflex takes longer to overwrite than a body takes to recover. You are on the right road, further back than you hoped.",
      "The number moved but the markers did not. Usually means the technique is landing while the foundation is being skipped. This one plateaus around week three if you leave it alone. Fix the sleep and the meals.",
      "Neither moved. Genuinely useful information, and the reason we measure rather than ask you how it felt. It points to one of three things: the foundation was not actually run, the sessions ran too hot — training at eight and nine builds tension rather than control — or there is something physical underneath. That is when bloodwork stops being optional. Take the list from Day 13 to a doctor.",
      "One thing worth saying plainly. If you have been honest with the conditions, whatever number you are looking at is real. That already puts you ahead of every man who has spent two years guessing.",
    ],
  },
  {
    slug: "finding-the-bottleneck",
    title: "Finding your bottleneck",
    minutes: 4,
    unlockDay: 13,
    body: [
      "The second half of this programme is heavier, and loading a system on top of an unresolved bottleneck is how men waste months. So before anything else: what is actually limiting you?",
      "If the number moved, your bottleneck is dose. You respond to this training and you have not had enough of it. Straight into the loading phase.",
      "If only the markers moved, your bottleneck is time or transfer. The base is repairing and the reflex has not caught up. Same route, but hold the ceiling at seven for longer and do not rush to eight.",
      "If nothing moved, stop training harder and find out why. The list for a doctor: blood pressure, fasting glucose or HbA1c, full blood count, ferritin, vitamin D, B12, thyroid function, and testosterone if your symptoms justify it. Add a gastric assessment if your stomach never settled. Undiagnosed diabetes, hypertension, thyroid disease, anaemia and low vitamin D all affect sexual function, all are common, and all are invisible until somebody runs the test.",
      "There is a fourth possibility worth naming. If you have pelvic aching, discomfort sitting, or a sense of being permanently clenched, your bottleneck may be tension you have just spent twelve days adding to. In that case the release work is your programme for the next fortnight and the contractions stop entirely.",
      "On ashwagandha, since men ask: there is some evidence for stress reduction and mixed evidence around testosterone in certain groups, but it is not a delay agent and it will not fix this. It also is not appropriate for everyone — avoid it with thyroid disease, autoimmune conditions or liver problems, and there are documented case reports of liver injury. Foundation first, then bloodwork, then medical correction if needed. Supplements are the last thing you reach for, not the first.",
    ],
  },
  {
    slug: "reverse-kegels",
    title: "Reverse kegels and letting go",
    minutes: 3,
    unlockDay: 14,
    body: [
      "A reverse kegel is the opposite of the exercise you already know. Instead of pulling the pelvic floor up and in, you gently push it down and out — the sensation is of the muscle lengthening rather than tightening.",
      "The easiest way to find it: lie on your back with your knees bent, put a hand on your belly, and breathe so the hand rises while your chest stays still. At the bottom of each exhale, let everything below release downward. It should feel like the beginning of letting go rather than any kind of effort.",
      "Two common mistakes. The first is pushing hard, as if straining — that recruits the abdominals and does nothing useful. The pressure should be barely there. The second is doing it while holding your breath, which guarantees you are tensing rather than releasing.",
      "Why this matters: two weeks of contractions builds strength and can also build resting tension, and a pelvic floor that never fully lets go is one of the recognised drivers of finishing fast. Every third day from here, you let go rather than hold on.",
      "If you have had any aching, any discomfort after sitting for long periods, or any sense of permanent clenching, this is the most valuable exercise in the entire programme for you, and you should be doing it daily rather than every third day.",
    ],
  },
  {
    slug: "the-training-week",
    title: "Structuring the training week",
    minutes: 3,
    unlockDay: 15,
    body: [
      "For twelve days the instruction was thirty to forty-five minutes of movement a day. That was correct for a fortnight and it is not enough for a month.",
      "The week from here: three strength sessions, two or three cardio sessions, walking on the other days, one genuine rest day.",
      "Strength work earns its place for a specific reason. It drives the circulatory and hormonal adaptations the whole system depends on, and over a month it does more for erection quality than anything you can buy in a bottle. You do not need a gym. Squats, press-ups, lunges, planks, hip bridges, and something to pull on if you can find one. Three sets of each, thirty minutes, three times a week.",
      "Cardio does a different job — it builds the aerobic base that determines how much you have left at the end of a long day, and it improves blood flow directly. Thirty to forty minutes at a pace where you can still talk but would rather not.",
      "The rest day is not laziness. Adaptation happens during recovery, not during the work, and men who train seven days a week through this phase tend to plateau in week three with worse sleep than they started with.",
    ],
  },
  {
    slug: "meal-rotations",
    title: "The seven-day meal rotation",
    minutes: 4,
    unlockDay: 16,
    regional: true,
    body: [
      "Eat well is what people write when they do not want to write a plan. Here is the plan. Run it on repeat; there is no benefit to variety for its own sake.",
      "Breakfast, rotate three: eggs with oats and a banana. Eggs with bread and avocado. Oats with milk or yoghurt, fruit and groundnuts. Every one of them has protein, a carbohydrate, fruit and fat, which is the only thing that matters.",
      "Lunch, rotate four: rice with chicken and vegetables. Plantain with fish and vegetables. Beans with plantain and eggs. Potatoes or yam with beef and vegetables. The rule underneath is the one from Day 1 — rice alone is not lunch, and neither are noodles alone.",
      "Dinner, same four with smaller portions, eaten five to six hours before you sleep.",
      "Two hours before bed: two bananas and a handful of tigernuts. If your stomach is unsettled, start with one small handful a day rather than four servings, and build up slowly. Tigernuts are high in fibre and fat, which is exactly what an irritated gut does not want in volume.",
      "Two things worth repeating. Water through the day, roughly half a litre every four hours as a floor. And electrolytes only after heavy sweating — a pinch of salt with a little sugar in one bottle — never routinely, and never at all if you have high blood pressure, kidney or heart problems.",
    ],
  },
  {
    slug: "the-conversation",
    title: "The conversation to have first",
    minutes: 3,
    unlockDay: 21,
    body: [
      "Most men try to run the partner phase in secret. It fails, and it fails for a predictable reason.",
      "You are about to start pausing, slowing down, staying still after entry, and changing position for no visible cause. To her, that reads as something being wrong. In the silence she will supply her own explanation — she is not attractive to you any more, you are thinking about someone else, you have lost interest. It is almost never the true one, and now you have created a second problem on top of the first.",
      "Ten seconds of honesty removes all of it. You do not have to make it a confession or a medical briefing. Something close to: I have been working on lasting longer, and part of it is slowing down and pausing on purpose. If I stop for a moment, nothing is wrong — it is the exercise.",
      "That is the whole conversation. What usually happens next surprises men: relief, and often more warmth than they expected, because she has probably noticed the tension and been constructing her own worse explanation for months.",
      "One more thing. Ask her to tell you if she wants to slow down too. This works better as something you are doing together than as a procedure you are performing on her, and the difference shows up in how the sessions actually go.",
    ],
  },
  {
    slug: "partner-stop-start",
    title: "Partner-assisted stop-start",
    minutes: 4,
    unlockDay: 23,
    body: [
      "Solo control does not transfer automatically, and finding that out during sex is demoralising. It is better to expect it.",
      "Another person raises arousal in ways your own hand cannot: unpredictability, novelty, and the weight of it mattering. Men who hold seven comfortably alone routinely find themselves at nine ninety seconds after a partner touches them. That is not the training failing. It is a different and harder version of the same skill, and it gets built the same way — from the bottom.",
      "So the phase starts below where you already are. Session one is manual stimulation only, no penetration, ceiling of six, three cycles. It will feel like going backwards. It is not: you are re-establishing that the scale still exists when someone else is holding it.",
      "Same rules as ever. Name your number to yourself. Stop at six. Release the pelvic floor rather than gripping it. Long exhale. Let it fall to three before restarting.",
      "Then it builds: entry with stillness on Day 25, movement with pauses on Day 27. Each step adds one variable. The men who rush straight to normal sex at this point tend to have one bad night and conclude the whole programme failed, when what actually failed was the sequencing.",
      "If you do not have a partner right now, repeat the Day 20 continuous session instead and come back to this phase later. Nothing is lost — the solo work is what it was built on.",
    ],
  },
  {
    slug: "pause-and-stay",
    title: "Pause and stay in",
    minutes: 3,
    unlockDay: 25,
    body: [
      "Entry is where most men in your position lose it. The spike of sensation and significance at that exact moment takes them from five to nine in seconds, and the whole thing is decided before it has begun.",
      "The instinctive response is to withdraw, wait, and go back in. It works, and it has a cost: it teaches your body that this level of stimulation is something to escape from. Do it enough and entry itself becomes a moment of dread, which brings the anxiety loop back into a situation you had almost solved.",
      "Pause and stay does the opposite. Enter, then stop completely. No movement at all for thirty seconds. Long exhale, pelvic floor deliberately soft, shoulders down. You stay inside and you let the arousal settle where it is.",
      "What this teaches is the thing you actually need: that high stimulation is survivable rather than something to run from. Most men find the first ten seconds hard and the next twenty surprisingly easy — arousal plateaus and then drifts down when nothing new is being added.",
      "If you reach seven, stay still for longer rather than moving. Only if you reach eight do you withdraw, wait, and re-enter. Withdrawal is the backup, not the plan.",
    ],
  },
  {
    slug: "positions",
    title: "Position as a control",
    minutes: 3,
    unlockDay: 27,
    body: [
      "Position is the last tool, and it is the one most men use backwards.",
      "Different positions deliver very different amounts of stimulation. You kneeling above her, with deep movement and full muscular engagement, is at the intense end. Her on top gives you far less — she controls the rhythm and depth, and your own muscles are not braced. You lying on your side is lower still. Shallow movement is considerably less intense than deep.",
      "So position is a dial. Turn it early, before you need it. The men who succeed in this phase change position at six, as a matter of routine, before anything is urgent. The men who struggle change at nine, as a rescue, and by then it is decided.",
      "Practical order for a session: start in the least stimulating position you both enjoy, use pauses to manage the climbs, and move to more intense positions later rather than earlier. That is the reverse of what most men do, which is to start with the most intense one and try to survive it.",
      "One caution worth keeping. None of this should turn sex into a technical exercise she can feel you performing. Use two tools a night, not five. The point of the training is that it eventually disappears into just being good at this — and by Day 30 most of it should already be automatic rather than managed.",
    ],
  },
  {
    slug: "maintenance",
    title: "Maintenance: holding what you built",
    minutes: 3,
    unlockDay: 30,
    body: [
      "What you built is a trained capacity, and trained capacities fade when training stops. Not overnight — over a couple of months, quietly, until one night you notice you are back somewhere you recognise.",
      "The maintenance protocol is deliberately small, because a maintenance plan you will not follow is worth nothing. Two sessions a week rather than five or six. The pelvic floor work, including the release side, three times a week. The foundation — sleep, three real meals, movement, water — which by now should not feel like a protocol at all. And one measurement a month, under the same four conditions, so you find out about a drift while it is still small.",
      "That monthly number matters more than the sessions. It is an early warning system, and it costs you nothing.",
      "The instruction men most need to hear at this point: retire the solo drill. It was scaffolding, and the building stands now. Keep the two weekly sessions as maintenance, not as a habit you have grown attached to. If you find yourself preferring the drill to sex, that is the signal to stop entirely and message us.",
      "If your number slips more than a couple of minutes over a month or two, do not panic and do not start again from Day 0. Run Days 15 to 22 — the loading block — for a fortnight. That is almost always enough.",
    ],
  },
];
