import type { Lesson } from "./lesson-types";

export const lessonsFr: Lesson[] = [
  {
    slug: "why-you-finish-fast",
    title: "Pourquoi vous finissez vite",
    minutes: 3,
    unlockDay: 0,
    body: [
      "L'éjaculation est un réflexe. Comme tout réflexe, elle a un seuil — un niveau d'excitation au-delà duquel le corps prend le relais et la décision ne vous appartient plus. Finir vite n'est pas un défaut de caractère et ce n'est presque jamais un manque de volonté. Cela signifie que votre seuil se situe plus bas que vous ne le voudriez, ou que vous ne sentez pas que vous en approchez.",
      "Trois choses abaissent ce seuil, et la plupart des hommes cumulent les trois à des degrés divers. La première est le conditionnement : des années à se dépêcher enseignent au système nerveux un chemin rapide de l'excitation vers la fin, et le système nerveux apprend remarquablement bien ce qu'on répète. La deuxième est l'anxiété : se surveiller augmente l'excitation, ce qui rapproche la fin, ce qui confirme la peur — une boucle qui se resserre à chaque tour. La troisième est la base physique : mauvais sommeil, absence de mouvement et troubles digestifs persistants laissent un système nerveux déjà réactif avant même que quoi que ce soit ne commence.",
      "Remarquez ce qui ne figure pas sur cette liste. La taille du pénis, la testostérone dans la plupart des cas, et une faiblesse morale. N'y figure pas non plus : le besoin d'un comprimé plus fort.",
      "Chacune de ces trois causes répond à l'entraînement plutôt qu'à la chimie. C'est toute la prémisse de ce programme, et c'est pourquoi nous commençons par mesurer — pour que dans douze jours vous regardiez une preuve plutôt que la promesse de quelqu'un.",
    ],
  },
  {
    slug: "how-to-measure",
    title: "Comment mesurer",
    minutes: 3,
    unlockDay: 1,
    body: [
      "Quatre étapes. C'est tout.",
      "1. Ouvrez Mesurer et cochez les 4 vérifications.",
      "2. Appuyez sur DÉMARRER dès que vous commencez.",
      "3. Faites normalement. N'essayez PAS de tenir. Pas de stop-and-go. N'utilisez aucune technique.",
      "4. Appuyez sur STOP dès que vous finissez. L'application garde le chiffre.",
      "La plupart des hommes le font tout seuls. C'est normal et c'est ce qu'on attend — vous n'avez besoin ni d'une partenaire ni de quelqu'un avec un chronomètre. Si vous préférez ne pas toucher votre téléphone sur le moment, regardez l'heure et entrez-la après. Il y a un bouton pour ça.",
      "Maintenant les quatre vérifications, et pourquoi chacune est là.",
      "2 jours depuis votre dernière fois. C'est celle que les hommes ratent le plus. Trois jours d'accumulation avant le Jour 12 contre deux heures avant le Jour 1 vous donnera un Jour 12 plus court et une fausse conclusion. Même écart les deux fois.",
      "Pas d'alcool aujourd'hui. Ça change votre résultat, et différemment à chaque fois.",
      "Pas de séance depuis hier. Une séance le même jour vous laisse émoussé.",
      "Même méthode les deux fois. Ce que vous choisissez au Jour 1 — chronomètre de l'app ou votre horloge — vous le reprenez au Jour 12.",
      "Une règle de plus : ce que vous faites au Jour 1, refaites-le au Jour 12. Seul les deux fois, ou avec une partenaire les deux fois. Jamais un de chaque. Ce sont deux mesures différentes et les comparer ne vous apprend rien.",
      "Dernière chose, et elle est honnête. Se chronométrer met la pression, et la pression fait finir plus vite. Votre chiffre du Jour 1 sera sans doute plus bas qu'une soirée normale. Ça n'a aucune importance — tant que le Jour 12 porte la même pression, la comparaison tient. C'est tout l'intérêt de garder les conditions identiques.",
    ],
  },
  {
    slug: "the-6-10-method",
    title: "La méthode 6/10",
    minutes: 5,
    unlockDay: 2,
    body: [
      "Demandez à un homme qui finit en deux minutes à quel chiffre il était trente secondes plus tôt. Il ne peut pas vous le dire. C'est tout le problème — la fin arrive sans prévenir parce que rien n'était surveillé pendant la montée.",
      "Voici donc l'échelle, avec ce que chaque niveau fait vraiment ressentir. Apprenez les sensations, pas les chiffres.",
      "1 à 4 — Excité, mais rien ne monte. Respiration normale. Vous pourriez vous arrêter et tenir une conversation.",
      "5 — Bien dur et à l'aise. Aucune tension nulle part. Rien ne tire.",
      "6 — C'EST VOTRE ARRÊT. Quatre signes, et un seul suffit : votre respiration se raccourcit sans que vous le décidiez ; un petit serrement en dessous, derrière les testicules ; ça commence à avancer tout seul ; vous sentez la première traction à la base.",
      "7 — Une montée nette à la base. Le ventre ou les cuisses se serrent. Vous devez vous concentrer pour rester stable. Déjà trop haut.",
      "8 — Vous luttez pour tenir. Orteils crispés, souffle bloqué, tout le corps tendu.",
      "9 — La sensation « ça y est ». Trop tard. Ça arrive, que vous le vouliez ou non.",
      "Comment s'en servir : dès la seconde où vous commencez, comptez dans votre tête. Trois. Quatre. Cinq. Dès que vous sentez UN SEUL des quatre signes du 6, arrêtez. Mains retirées. N'attendez pas d'être sûr — si vous êtes sûr, vous êtes déjà à 7.",
      "Puis attendez. Depuis 6, comptez 60 à 90 secondes. Depuis 7, plutôt 2 minutes. Ne regardez pas l'horloge. Repartez seulement quand la sensation de traction a complètement disparu.",
      "Vous vous entraînez à 6 et 7. Vous n'allez jamais à 9 volontairement. Les hommes veulent toujours contester ça parce que tenir au bord paraît plus courageux. Ça ne l'est pas. À 9 vous allez serrer pour survivre, et serrer est exactement la tension qui fait finir vite au départ. Vous répéteriez le problème.",
      "S'arrêter à 6 vous apprend à conduire. S'arrêter à 9 vous apprend à paniquer avec un meilleur timing.",
      "Dernière chose. La plupart des hommes n'ont jamais remarqué le 6 de leur vie. Si votre première séance se termine en le dépassant directement, ce n'est pas un échec — c'est le résultat. Vos deux premières séances servent uniquement à localiser le 6. Durer vient après.",
    ],
  },
  {
    slug: "pelvic-floor",
    title: "Le périnée : contracter et relâcher",
    minutes: 4,
    unlockDay: 3,
    body: [
      "Presque tous les articles écrits sur le sujet disent aux hommes de faire des Kegels, et presque tous ne décrivent que la moitié de l'exercice. La contraction est la moitié que tout le monde connaît. Le relâchement est la moitié qui gouverne le contrôle.",
      "Voici ce qui compte et que la plupart des hommes n'ont jamais entendu : une part notable des éjaculations précoces vient d'un périnée trop tendu, et non trop faible. Pour ces hommes, contracter davantage aggrave les choses. Si vous avez des douleurs pelviennes, une gêne après être resté assis longtemps, ou une sensation de crispation permanente, vous en faites probablement partie.",
      "Le test est simple. Faites dix contractions et concentrez-vous sur le relâchement. Si lâcher vous paraît flou, incomplet, ou si le muscle reste à moitié engagé, votre problème est la tension et non la force.",
      "Protocole standard : trois séries de dix, deux fois par jour. Contractez cinq secondes, relâchez cinq secondes, et que le relâchement ne soit jamais plus court que la contraction. Respirez pendant l'exercice — la plupart des hommes bloquent leur souffle, ce qui recrute exactement les mauvais muscles.",
      "Variante « relâchement seul », pour les hommes décrits plus haut : supprimez complètement les contractions. Faites des kegels inversés — une légère poussée vers le bas et l'extérieur à chaque expiration — plus une respiration ventrale lente, deux fois par jour. Revenez aux contractions après deux semaines, une fois que lâcher vous paraît complet.",
      "Et ne passez pas la journée crispé. Vous entraînez un muscle à vous obéir, pas à rester au garde-à-vous en permanence.",
    ],
  },
  {
    slug: "breathing",
    title: "La respiration et le système nerveux",
    minutes: 3,
    unlockDay: 4,
    body: [
      "La respiration a l'air d'être la partie molle du programme. C'est la partie au mécanisme physique le plus direct.",
      "L'éjaculation est pilotée par le système nerveux sympathique — la même branche qui gère la fuite ou le combat. Tout ce qui élève le tonus sympathique rapproche le seuil : le stress, l'adrénaline, une respiration courte et rapide, un corps crispé. Tout ce qui l'abaisse vous achète de la marge.",
      "Une longue expiration est le levier le plus rapide dont vous disposez. Quand vous expirez lentement, la branche parasympathique est engagée directement, le rythme cardiaque baisse en quelques battements et la tension musculaire suit. Inspirez sur quatre par le nez, expirez sur six par la bouche. Cela fonctionne en quelques secondes et ne demande rien.",
      "C'est pourquoi chaque séance commence par deux minutes de respiration, et pourquoi vous expirez longuement à chaque arrêt. Vous ne vous calmez pas comme on adopte une humeur. Vous abaissez le niveau de départ de votre système nerveux, pour que la même stimulation atterrisse plus bas sur l'échelle.",
      "Observez une fois votre respiration pendant un rapport et vous verrez le problème : elle devient courte, haute dans la poitrine, et s'arrête souvent complètement vers la fin. Ce schéma accélère tout. Respirer volontairement bas et lentement est le changement le plus facile que vous puissiez faire dès ce soir.",
    ],
  },
  {
    slug: "why-pills-fail",
    title: "Pourquoi les comprimés aggravent les choses",
    minutes: 4,
    unlockDay: 5,
    body: [
      "Ce n'est pas un argument moral. C'est un argument mécanique.",
      "Voici ce qu'on oublie. Chaque bonne soirée passée avec un comprimé vous apprend une chose : que vous avez besoin du comprimé. Et avoir peur de ne pas y arriver sans aide est en soi une des causes directes de finir vite. Vous vous retrouvez donc avec le problème de départ, plus une nouvelle peur par-dessus. Le comprimé règle ce soir et rend le mois prochain plus dur.",
      "Les sprays retardants ont un second coût, plus subtil. Ils réduisent la sensation, ce qui semble utile et ne l'est pas : votre capacité à sentir où vous êtes sur l'échelle est précisément la compétence dont vous avez besoin. Vous anesthésier vous rend moins capable de vous lire, si bien qu'à la fin du flacon vous n'êtes pas revenu au point de départ, vous êtes légèrement en dessous.",
      "L'alcool échange une heure d'anxiété réduite contre une érection dégradée, un sommeil dégradé et une récupération dégradée. C'est un mauvais échange à chaque fois, et il fausse toute mesure que vous prendriez.",
      "Reste la catégorie vendue comme naturelle. Des autorités sanitaires du monde entier ont trouvé à plusieurs reprises des médicaments non déclarés — les mêmes molécules que les comprimés sur ordonnance — dans des compléments présentés comme à base de plantes. Si vous en preniez, vous preniez peut-être déjà la molécule que vous pensiez éviter, à dose inconnue, sans étiquette et sans aucun moyen de savoir ce que contenait la gélule.",
      "Une exception importante. Si un médecin vous a prescrit quelque chose, ne l'arrêtez pas de vous-même. Parlez-en à celui qui vous l'a prescrit. Ce programme accompagne un suivi médical ; il ne le remplace pas.",
    ],
  },
  {
    slug: "sleep-and-food",
    title: "Sommeil, alimentation et qualité de l'érection",
    minutes: 3,
    unlockDay: 6,
    body: [
      "Des hommes accepteront un entraînement difficile et inconfortable pendant des semaines et refuseront de se coucher une heure plus tôt. Le sommeil est le point le plus rentable de tout ce programme, et il est gratuit.",
      "L'essentiel de la production de testostérone se fait pendant le sommeil, et des nuits courtes ou hachées la réduisent de façon mesurable. Le sommeil détermine aussi la réactivité de votre système nerveux le lendemain — un corps en manque de sommeil est déjà plus proche de l'état d'alerte avant même que quoi que ce soit n'arrive, ce qui fait que chaque stimulation atterrit plus haut sur votre échelle.",
      "Les érections matinales sont le diagnostic le moins cher dont vous disposez. Elles suivent la qualité du sommeil, la circulation et l'état hormonal, et quand les hommes de ce programme commencent à progresser, ce sont elles qui bougent en premier — souvent dès la première semaine, bien avant le chronomètre. Surveillez-les.",
      "L'alimentation compte de façon plus simple que ne le suggère la plupart des contenus. Vous n'êtes pas au régime et vous ne supprimez rien. Trois vrais repas avec protéines, féculent, légumes et gras, pris à peu près aux mêmes heures chaque jour, le dernier assez tôt pour ne pas vous coucher plein. C'est toute la consigne.",
      "La raison pour laquelle nous insistons sur le dîner tôt et la collation d'avant coucher est le sommeil, pas la digestion. Se coucher l'estomac plein perturbe le sommeil ; se coucher affamé vous réveille à trois heures du matin. La banane et le souchet occupent l'espace entre ces deux échecs.",
    ],
  },
  {
    slug: "the-stomach-connection",
    title: "Le lien avec l'estomac",
    minutes: 3,
    unlockDay: 7,
    body: [
      "C'est la partie du programme que les hommes trouvent la plus étrange, et pour une minorité notable elle se révèle être tout le goulot d'étranglement.",
      "Si votre estomac vous fait mal presque tous les jours — brûlures, reflux, ballonnements, nausées, appétit qui va et vient — ce n'est pas un problème séparé placé à côté de celui-ci. Il est en amont. Des troubles gastriques persistants ruinent le sommeil, coupent l'appétit, vident l'énergie et maintiennent le corps dans un état de stress de bas niveau. Chacun de ces effets abaisse votre seuil.",
      "Entraîner le contrôle éjaculatoire pendant que l'intestin est enflammé, c'est régler un moteur qui fuit. Le réglage n'est pas mauvais. Il est simplement défait plus vite que vous ne pouvez le faire.",
      "Nous suivons donc le confort digestif à côté du reste, chaque soir, pendant tout le programme. Si la fondation le règle — et des repas réguliers, moins d'alcool et un meilleur sommeil y parviennent souvent — vous le verrez dans le journal en deux semaines.",
      "Si cela ne se calme pas, c'est une conversation à avoir avec un médecin plutôt qu'un protocole de plus. Un reflux, des brûlures ou des ballonnements persistants méritent un vrai bilan ; selon vos symptômes et vos antécédents, cela peut inclure la recherche d'H. pylori, d'un ulcère ou d'un reflux pathologique. Ignorer cela et acheter un complément plus fort est le chemin coûteux vers le même endroit.",
    ],
  },
  {
    slug: "not-a-habit",
    title: "Un exercice, pas une habitude",
    minutes: 2,
    unlockDay: 9,
    body: [
      "Il existe un vrai risque dans un programme comme celui-ci, et il serait malhonnête de ne pas le nommer : un exercice fait seul, plusieurs fois par semaine, à heures fixes, peut discrètement cesser d'être un entraînement pour devenir une habitude.",
      "La structure est délibérément conçue contre cela. Les séances sont prescrites plutôt que faites sur impulsion. Leur durée est plafonnée. Elles ont lieu à des horaires prévus. Rien ne se passe en dehors. Si vous avez une partenaire, un rapport remplace une séance au lieu de s'y ajouter. Et des jours de repos sont intégrés, qui ne sont pas facultatifs.",
      "La règle « pas d'écran » relève de la même logique. Les écrans ne sont pas interdits pour des raisons morales — ils le sont parce qu'une stimulation visuelle très intense renforce exactement le conditionnement que vous passez douze jours à réécrire.",
      "Deux signaux à surveiller. Si vous vous surprenez à attendre la séance plus que le rapport avec votre partenaire, arrêtez et écrivez-nous. Si vous faites des séances supplémentaires hors du plan, arrêtez et écrivez-nous. Aucun des deux ne signifie que vous avez mal fait ; les deux signifient que le plan doit être ajusté à vous.",
      "L'objectif est de mettre cet exercice à la retraite. À la fin du Sprint de 30 jours, le travail est passé dans le rapport à deux, là où il devait toujours aboutir. On démonte l'échafaudage quand le bâtiment tient debout.",
    ],
  },
  {
    slug: "reading-your-result",
    title: "Comment lire votre résultat",
    minutes: 4,
    unlockDay: 12,
    body: [
      "Il y a quatre issues possibles et trois sont de bonnes nouvelles.",
      "Le chiffre a bougé et les indicateurs ont monté. L'issue la plus claire. Le mécanisme fonctionne sur vous et la dose est votre variable restante — la même chose, en plus chargé, puis transférée vers le rapport à deux.",
      "Les indicateurs ont monté mais le chronomètre a peu bougé. C'est le résultat le plus fréquent à douze jours et ce n'est pas un échec. L'énergie, le sommeil, les érections matinales et votre propre sensation de contrôle bougent avant le réflexe, car un réflexe met plus de temps à être réécrit qu'un corps à récupérer. Vous êtes sur la bonne route, un peu plus en arrière que vous ne l'espériez.",
      "Le chiffre a bougé mais pas les indicateurs. Cela signifie généralement que la technique fonctionne pendant que la fondation est sautée. Celle-ci plafonne vers la troisième semaine si vous n'y touchez pas. Corrigez le sommeil et les repas.",
      "Ni l'un ni l'autre n'a bougé. Information réellement utile, et la raison pour laquelle nous mesurons au lieu de vous demander ce que vous avez ressenti. Cela oriente vers trois possibilités : la fondation n'a pas vraiment été appliquée, les séances tournaient trop haut — s'entraîner à huit et neuf construit de la tension et non du contrôle — ou il y a quelque chose de physique en dessous. C'est le moment où le bilan sanguin cesse d'être facultatif. Emportez la liste du Jour 13 chez un médecin.",
      "Une chose mérite d'être dite clairement. Si vous avez été honnête avec les conditions, le chiffre que vous regardez est réel. Cela vous place déjà devant tous les hommes qui passent deux ans à deviner.",
    ],
  },
  {
    slug: "finding-the-bottleneck",
    title: "Trouver votre blocage",
    minutes: 4,
    unlockDay: 13,
    body: [
      "La seconde moitié de ce programme est plus lourde, et charger un système par-dessus un blocage non résolu est la façon dont les hommes perdent des mois. Donc avant tout : qu'est-ce qui vous limite réellement ?",
      "Si le chiffre a bougé, votre blocage est la dose. Vous répondez à cet entraînement et vous n'en avez pas eu assez. Directement en phase de charge.",
      "Si seuls les indicateurs ont bougé, votre blocage est le temps ou le transfert. La base se répare et le réflexe n'a pas suivi. Même route, mais maintenez le plafond à sept plus longtemps et ne vous précipitez pas vers huit.",
      "Si rien n'a bougé, cessez de vous entraîner plus dur et cherchez pourquoi. La liste à apporter au médecin : tension artérielle, glycémie à jeun ou HbA1c, numération formule sanguine, ferritine, vitamine D, B12, bilan thyroïdien, et testostérone si vos symptômes le justifient. Ajoutez un bilan gastrique si votre estomac ne s'est jamais calmé. Un diabète non diagnostiqué, une hypertension, une maladie thyroïdienne, une anémie et une carence en vitamine D affectent tous la fonction sexuelle, sont tous fréquents, et sont tous invisibles tant que personne ne fait le test.",
      "Une quatrième possibilité mérite d'être nommée. Si vous avez des douleurs pelviennes, une gêne en position assise, ou une sensation de crispation permanente, votre blocage peut être une tension que vous venez de passer douze jours à alimenter. Dans ce cas, le travail de relâchement est votre programme pour les deux semaines à venir et les contractions s'arrêtent complètement.",
      "Sur l'ashwagandha, puisque les hommes posent la question : il existe quelques données sur la réduction du stress et des données contradictoires sur la testostérone dans certains groupes, mais ce n'est pas un retardateur et cela ne réglera pas ceci. Ce n'est pas non plus adapté à tout le monde — à éviter en cas de maladie thyroïdienne, de maladie auto-immune ou de problème hépatique, et il existe des cas documentés d'atteinte du foie. La fondation d'abord, puis le bilan sanguin, puis la correction médicale si nécessaire. Les compléments sont la dernière chose vers laquelle on se tourne, pas la première.",
    ],
  },
  {
    slug: "reverse-kegels",
    title: "Les kegels inversés et le lâcher-prise",
    minutes: 3,
    unlockDay: 14,
    body: [
      "Un kegel inversé est l'inverse de l'exercice que vous connaissez déjà. Au lieu de tirer le périnée vers le haut et l'intérieur, vous le poussez doucement vers le bas et l'extérieur — la sensation est celle d'un muscle qui s'allonge plutôt qui se resserre.",
      "La façon la plus simple de le trouver : allongez-vous sur le dos, genoux pliés, une main sur le ventre, et respirez de sorte que la main monte pendant que la poitrine reste immobile. Au bas de chaque expiration, laissez tout ce qui est en dessous se relâcher vers le bas. Cela doit ressembler à un début de lâcher-prise plutôt qu'à un effort.",
      "Deux erreurs fréquentes. La première est de pousser fort, comme si l'on forçait — cela recrute les abdominaux et ne sert à rien. La pression doit être à peine présente. La seconde est de le faire en bloquant sa respiration, ce qui garantit que vous vous crispez au lieu de relâcher.",
      "Pourquoi cela compte : deux semaines de contractions construisent de la force et peuvent aussi construire une tension de repos, et un périnée qui ne se relâche jamais complètement est l'un des facteurs reconnus de la rapidité. Tous les trois jours à partir d'ici, vous lâchez au lieu de tenir.",
      "Si vous avez ressenti la moindre douleur, la moindre gêne après être resté assis longtemps, ou une crispation permanente, c'est l'exercice le plus utile de tout le programme pour vous, et vous devriez le faire quotidiennement plutôt que tous les trois jours.",
    ],
  },
  {
    slug: "the-training-week",
    title: "Structurer la semaine d'entraînement",
    minutes: 3,
    unlockDay: 15,
    body: [
      "Pendant douze jours, la consigne était de trente à quarante-cinq minutes de mouvement par jour. C'était juste pour quinze jours et ce n'est pas suffisant pour un mois.",
      "La semaine à partir d'ici : trois séances de renforcement, deux à trois séances de cardio, de la marche les autres jours, un vrai jour de repos.",
      "Le renforcement mérite sa place pour une raison précise. Il déclenche les adaptations circulatoires et hormonales dont tout le système dépend, et sur un mois il fait davantage pour la qualité de l'érection que tout ce qui se vend en flacon. Vous n'avez pas besoin d'une salle. Squats, pompes, fentes, gainage, ponts fessiers, et quelque chose à tirer si vous en trouvez. Trois séries de chaque, trente minutes, trois fois par semaine.",
      "Le cardio remplit une autre fonction — il construit la base aérobie qui détermine ce qu'il vous reste au bout d'une longue journée, et il améliore directement la circulation. Trente à quarante minutes à une allure où vous pouvez encore parler mais préféreriez éviter.",
      "Le jour de repos n'est pas de la paresse. L'adaptation se produit pendant la récupération, pas pendant l'effort, et les hommes qui s'entraînent sept jours sur sept dans cette phase plafonnent en troisième semaine avec un sommeil pire qu'au départ.",
    ],
  },
  {
    slug: "meal-rotations",
    title: "La rotation de repas sur sept jours",
    minutes: 4,
    unlockDay: 16,
    regional: true,
    body: [
      "« Mangez bien » est ce qu'on écrit quand on ne veut pas écrire un plan. Voici le plan. Répétez-le en boucle ; la variété pour elle-même n'apporte rien.",
      "Petit-déjeuner, trois options en rotation : œufs, bouillie d'avoine et banane. Œufs, pain et avocat. Avoine avec lait ou yaourt, fruits et arachides. Chacune contient des protéines, un féculent, un fruit et du gras, ce qui est la seule chose qui compte.",
      "Déjeuner, quatre options en rotation : riz, poulet et légumes. Plantain, poisson et légumes. Haricots, plantain et œufs. Pommes de terre ou igname, bœuf et légumes. La règle sous-jacente est celle du Jour 1 — le riz seul n'est pas un déjeuner, les pâtes instantanées seules non plus.",
      "Dîner, les mêmes quatre en portions plus petites, cinq à six heures avant de dormir.",
      "Deux heures avant le coucher : deux bananes et une poignée de souchet. Si votre estomac est fragile, commencez par une petite poignée par jour plutôt que quatre portions, et augmentez lentement. Le souchet est très riche en fibres et en gras, ce qu'un intestin irrité ne veut surtout pas en quantité.",
      "Deux choses à répéter. De l'eau toute la journée, environ un demi-litre toutes les quatre heures comme minimum. Et des électrolytes uniquement après une forte transpiration — une pincée de sel avec un peu de sucre dans une bouteille — jamais en routine, et jamais du tout en cas d'hypertension, de problème rénal ou cardiaque.",
    ],
  },
  {
    slug: "the-conversation",
    title: "La conversation à avoir d'abord",
    minutes: 3,
    unlockDay: 21,
    body: [
      "La plupart des hommes tentent de mener la phase à deux en secret. Cela échoue, et pour une raison prévisible.",
      "Vous allez commencer à faire des pauses, à ralentir, à rester immobile après la pénétration et à changer de position sans cause visible. Pour elle, cela signifie que quelque chose ne va pas. Dans le silence, elle fournira sa propre explication — elle ne vous plaît plus, vous pensez à quelqu'un d'autre, vous avez perdu l'intérêt. Ce n'est presque jamais la bonne, et vous venez de créer un second problème par-dessus le premier.",
      "Dix secondes d'honnêteté suppriment tout cela. Vous n'avez pas besoin d'en faire une confession ni un exposé médical. Quelque chose comme : je travaille sur ma durée, et une partie du travail consiste à ralentir et à faire des pauses volontairement. Si je m'arrête un instant, rien ne va mal — c'est l'exercice.",
      "C'est toute la conversation. Ce qui suit surprend souvent les hommes : du soulagement, et souvent plus de chaleur qu'attendu, car elle a probablement remarqué la tension et se construisait sa propre explication, pire, depuis des mois.",
      "Une dernière chose. Demandez-lui de vous dire si elle aussi veut ralentir. Cela fonctionne bien mieux comme quelque chose que vous faites ensemble que comme une procédure que vous exécutez sur elle, et la différence se voit dans le déroulement réel des séances.",
    ],
  },
  {
    slug: "partner-stop-start",
    title: "Le stop-start avec partenaire",
    minutes: 4,
    unlockDay: 23,
    body: [
      "Le contrôle en solo ne se transfère pas automatiquement, et le découvrir en pleine action est démoralisant. Mieux vaut s'y attendre.",
      "Une autre personne augmente l'excitation d'une façon que votre propre main ne peut pas : imprévisibilité, nouveauté, et le poids de l'enjeu. Des hommes qui tiennent sept confortablement seuls se retrouvent couramment à neuf quatre-vingt-dix secondes après qu'une partenaire les a touchés. Ce n'est pas l'entraînement qui échoue. C'est une version différente et plus difficile de la même compétence, et elle se construit de la même manière — depuis le bas.",
      "La phase commence donc en dessous de là où vous êtes déjà. La première séance est une stimulation manuelle uniquement, sans pénétration, plafond de six, trois cycles. Vous aurez l'impression de reculer. Ce n'est pas le cas : vous rétablissez le fait que l'échelle existe encore quand c'est quelqu'un d'autre qui la tient.",
      "Mêmes règles que d'habitude. Nommez votre chiffre. Arrêtez à six. Relâchez le périnée au lieu de le serrer. Longue expiration. Laissez redescendre à trois avant de reprendre.",
      "Puis cela se construit : entrée avec immobilité au Jour 25, mouvement avec pauses au Jour 27. Chaque étape ajoute une variable. Les hommes qui se précipitent vers un rapport normal à ce stade ont généralement une mauvaise soirée et concluent que tout le programme a échoué, alors que ce qui a échoué est l'ordre des étapes.",
      "Si vous n'avez pas de partenaire actuellement, répétez la séance continue du Jour 20 et revenez à cette phase plus tard. Rien n'est perdu — le travail solo est la fondation de tout le reste.",
    ],
  },
  {
    slug: "pause-and-stay",
    title: "Pause et reste à l'intérieur",
    minutes: 3,
    unlockDay: 25,
    body: [
      "L'entrée est le moment où la plupart des hommes dans votre situation perdent pied. Le pic de sensation et de signification à cet instant précis les fait passer de cinq à neuf en quelques secondes, et tout est joué avant même d'avoir commencé.",
      "La réaction instinctive est de se retirer, d'attendre, puis d'entrer à nouveau. Cela fonctionne, et cela a un coût : votre corps apprend que ce niveau de stimulation est quelque chose à fuir. Répétez-le assez souvent et l'entrée devient elle-même un moment d'appréhension, ce qui ramène la boucle d'anxiété dans une situation que vous aviez presque réglée.",
      "« Pause et reste » fait l'inverse. Entrez, puis arrêtez complètement. Aucun mouvement pendant trente secondes. Longue expiration, périnée volontairement souple, épaules basses. Vous restez à l'intérieur et vous laissez l'excitation se stabiliser là où elle est.",
      "Ce que cela enseigne est exactement ce dont vous avez besoin : qu'une stimulation forte est survivable au lieu d'être quelque chose à fuir. La plupart des hommes trouvent les dix premières secondes difficiles et les vingt suivantes étonnamment faciles — l'excitation plafonne puis redescend doucement quand rien de nouveau ne s'ajoute.",
      "Si vous atteignez sept, restez immobile plus longtemps au lieu de bouger. Ce n'est qu'à huit que vous vous retirez, attendez et entrez à nouveau. Le retrait est la solution de secours, pas le plan.",
    ],
  },
  {
    slug: "positions",
    title: "La position comme réglage",
    minutes: 3,
    unlockDay: 27,
    body: [
      "La position est le dernier outil, et c'est celui que la plupart des hommes utilisent à l'envers.",
      "Les positions délivrent des quantités de stimulation très différentes. Vous à genoux au-dessus d'elle, avec un mouvement profond et un engagement musculaire complet, se situe à l'extrémité intense. Elle au-dessus vous en donne bien moins — elle contrôle le rythme et la profondeur, et vos propres muscles ne sont pas crispés. Vous allongé sur le côté, c'est encore plus bas. Un mouvement peu profond est nettement moins intense qu'un mouvement profond.",
      "La position est donc un bouton. Tournez-le tôt, avant d'en avoir besoin. Les hommes qui réussissent cette phase changent de position à six, par habitude, avant que rien ne soit urgent. Ceux qui galèrent changent à neuf, en sauvetage, et à ce moment-là c'est joué.",
      "Ordre pratique pour une séance : commencez par la position la moins stimulante que vous appréciez tous les deux, utilisez les pauses pour gérer les montées, et passez aux positions plus intenses plus tard plutôt que plus tôt. C'est l'inverse de ce que font la plupart des hommes, qui commencent par la plus intense et essaient d'y survivre.",
      "Une précaution à garder. Rien de tout cela ne doit transformer le rapport en exercice technique qu'elle sent que vous exécutez. Utilisez deux outils par soirée, pas cinq. Le but de l'entraînement est qu'il finisse par disparaître dans le simple fait d'être bon — et au Jour 30, l'essentiel devrait déjà être automatique plutôt que piloté.",
    ],
  },
  {
    slug: "maintenance",
    title: "L'entretien : conserver ce que vous avez construit",
    minutes: 3,
    unlockDay: 30,
    body: [
      "Ce que vous avez construit est une capacité entraînée, et les capacités entraînées s'effacent quand l'entraînement s'arrête. Pas du jour au lendemain — en quelques mois, discrètement, jusqu'au soir où vous constatez que vous êtes revenu quelque part que vous reconnaissez.",
      "Le protocole d'entretien est volontairement léger, car un plan d'entretien que vous ne suivrez pas ne vaut rien. Deux séances par semaine au lieu de cinq ou six. Le travail du périnée, relâchement compris, trois fois par semaine. La fondation — sommeil, trois vrais repas, mouvement, eau — qui à ce stade ne devrait plus ressembler à un protocole. Et une mesure par mois, dans les mêmes quatre conditions, pour repérer une dérive tant qu'elle est petite.",
      "Ce chiffre mensuel compte plus que les séances. C'est un système d'alerte précoce, et il ne vous coûte rien.",
      "La consigne dont les hommes ont le plus besoin ici : mettez l'exercice solo à la retraite. C'était un échafaudage, et le bâtiment tient maintenant. Gardez les deux séances hebdomadaires comme entretien, pas comme une habitude à laquelle vous vous seriez attaché. Si vous vous surprenez à préférer l'exercice au rapport, c'est le signal d'arrêter complètement et de nous écrire.",
      "Si votre chiffre glisse de plus de deux ou trois minutes sur un ou deux mois, ne paniquez pas et ne repartez pas du Jour 0. Refaites les Jours 15 à 22 — le bloc de charge — pendant deux semaines. C'est presque toujours suffisant.",
    ],
  },
];
