import type { Protocol, ProtocolDay } from "./protocol-types";

const rulesIntro = [
  "Ceci se fait chaque jour, du Jour 0 jusqu'à la fin.",
  "C'est la partie ennuyeuse. C'est aussi celle que la plupart des hommes sautent - et c'est pour ça que la plupart n'avancent pas.",
  "Ce n'est pas un régime. Vous ne supprimez rien. Vous réparez le carburant, la circulation et le sommeil - les trois choses qui décident de ce qui vous reste à 23h.",
];

const rules = [
  {
    id: "water",
    label: "Buvez de l'eau toute la journée",
    detail:
      "Un demi-litre toutes les 4 heures, minimum. Plus s'il fait chaud ou si vous avez beaucoup transpiré. Après grosse transpiration : une pincée de sel et un peu de sucre dans une bouteille. PAS de sel si vous avez de l'hypertension, un problème de reins ou de cœur - et si vous n'avez jamais fait vérifier votre tension, faites-la vérifier et buvez de l'eau plate en attendant.",
  },
  {
    id: "breakfast",
    label: "Vrai petit-déjeuner, 7h-8h",
    detail:
      "Protéine + féculent + fruit + un peu de gras. Œufs, bouillie et banane. Œufs, pain et avocat. Avoine avec lait, fruits et arachides. Ne sautez pas le petit-déjeuner pour manger un seul gros repas à 15h - c'est pour ça que vous êtes vidé le soir.",
    regional: true,
  },
  {
    id: "lunch",
    label: "Vrai déjeuner, vers midi",
    detail:
      "Féculent + protéine + légumes + gras. Le riz seul n'est pas un repas. Les pâtes seules non plus. Si vous mangez du riz ou des pâtes, ça vient avec des œufs, du poisson, du poulet, du bœuf ou des haricots, plus des légumes.",
    regional: true,
  },
  {
    id: "dinner",
    label: "Dîner, 5-6 heures avant de dormir",
    detail:
      "Comme le déjeuner. Assez tôt pour ne pas vous coucher plein. Vous dormez à 22h, mangez à 16h-17h. Vous dormez à minuit, 18h-19h ça va. C'est l'écart qui compte, pas l'heure.",
    regional: true,
  },
  {
    id: "snack",
    label: "2 bananes + une poignée de souchet, 2 heures avant le coucher",
    detail:
      "Ca évite que la faim vous réveille à 3h du matin. Le souchet est lourd en fibres - si votre estomac est déjà fragile, commencez par UNE petite poignée par jour, pas quatre. Si ça aggrave les gaz, arrêtez. Ça aide ; ce n'est pas le remède.",
    regional: true,
  },
  {
    id: "move",
    label: "Bougez 30-45 minutes",
    detail:
      "Marche, jogging, vélo, natation, football. À n'importe quelle heure. Vous construisez la circulation, vous ne vous détruisez pas. La marche compte. Tous les jours.",
  },
  {
    id: "sleep",
    label: "7-8 heures, a la même heure chaque nuit",
    detail:
      "C'est le plus important de la liste et c'est gratuit. Le sommeil commande votre testostérone, vos érections, et la nervosité de votre système nerveux. Même heure de coucher. Téléphone posé les 30 dernières minutes.",
  },
  {
    id: "alcohol",
    label: "Pas d'alcool pendant les 12 jours",
    detail:
      "Il détruit votre sommeil, vos érections et votre récupération, et il faussera votre mesure. Douze jours.",
  },
  {
    id: "screens",
    label: "Pas de porno pendant le programme",
    detail:
      "Les séances se font à la main, sans écran. Si votre problème est le conditionnement, les écrans entraînent exactement ce que vous essayez de défaire. Ce n'est pas une question de morale. C'est mécanique.",
  },
  {
    id: "discipline",
    label: "Faites uniquement les séances que l'application donne",
    detail:
      "Aux heures prévues. Rien en plus. Pas de masturbation supplémentaire pendant les 12 jours. Si vous avez une partenaire, un rapport REMPLACE une séance, il ne s'ajoute pas. Le but est de ne plus avoir besoin de cet exercice. Si vous attendez la séance plus que le rapport, arrêtez et écrivez-nous.",
  },
  {
    id: "log",
    label: "Notez vos indicateurs chaque soir",
    detail:
      "60 secondes avant de dormir. C'est comme ça que vous voyez les progrès les jours où le chrono n'a pas encore bougé - et ce sont eux qui bougént en premier.",
  },
];

const days: ProtocolDay[] = [
  {
    day: 0,
    kind: "reset",
    phase: "Fondation",
    title: "Remise à zéro",
    focus: "Nettoyer le système. Pas d'entraînement aujourd'hui.",
    lesson: "why-you-finish-fast",
    brief: [
      "Aujourd'hui vous ne faites rien. Pas d'entraînement.",
      "Demain vous prenez votre chiffre. Ce chiffre décide de tout, donc ce soir doit être propre.",
      "Pas d'alcool. Pas de drogue. Mangez correctement. Dormez une nuit complète. Et ne jouissez pas ce soir — il vous faut 2 jours nets avant de mesurer.",
      "Si vous avez joui dans les 2 derniers jours, reculez votre mesure d'un jour.",
      "Autre chose : surveillez votre estomac aujourd'hui. Brûlures, gaz, reflux, douleurs, pas d'appétit. Notez ce que vous sentez. Ça compte plus que vous ne croyez.",
    ],
    tasks: [
      { id: "d0-alcohol", kind: "foundation", label: "Pas d'alcool ni de drogues aujourd'hui" },
      {
        id: "d0-abstain",
        kind: "foundation",
        label: "Pas d'éjaculation — la fenêtre de 48 h commence maintenant",
        detail: "Si vous avez fini dans les 48 dernières heures, reculez la mesure d'un jour.",
      },
      { id: "d0-meals", kind: "foundation", label: "Trois vrais repas, de l'eau toute la journée" },
      { id: "d0-sleep", kind: "foundation", label: "Une nuit complète, à heure fixe" },
      {
        id: "d0-stomach",
        kind: "foundation",
        label: "Notez vos symptômes digestifs",
        detail: "Brûlures, reflux, nausées, ballonnements, appétit faible, gêne récurrente.",
      },
      {
        id: "d0-bp",
        kind: "medical",
        label: "Faites vérifier votre tension cette semaine si ce n'a jamais été fait",
      },
      { id: "d0-lesson", kind: "lesson", label: "Lire : Pourquoi vous finissez vite" },
    ],
  },
  {
    day: 1,
    kind: "baseline",
    phase: "Fondation",
    title: "Mesure de départ",
    focus: "Obtenez votre chiffre. N'essayez pas d'impressionner.",
    lesson: "how-to-measure",
    brief: [
      "Aujourd'hui vous prenez votre chiffre.",
      "Faites normalement. N'essayez PAS de tenir. N'utilisez aucune technique. Un bon chiffre aujourd'hui ne fait que rendre le Jour 12 moins bon.",
      "Allez dans Mesurer. Cochez les 4 points. DÉMARRER quand vous commencez, STOP quand vous finissez. L'application garde le chiffre.",
      "La plupart des hommes le font seuls. C'est normal et c'est ce qu'on attend. Assurez-vous juste de faire le Jour 12 de la même façon.",
      "Puis commencez les kegels ce soir — 3 séries de 10, deux fois. Serrez 5 secondes, relâchez 5 secondes. Relâcher compte plus que serrer.",
    ],
    tasks: [
      {
        id: "d1-conditions",
        kind: "measure",
        label: "Confirmez les quatre conditions du test",
        detail: "48 h sans éjaculation, pas d'alcool, pas de séance depuis 24 h, méthode reproductible.",
      },
      { id: "d1-mode", kind: "measure", label: "Choisissez votre mode — seul ou avec une partenaire" },
      { id: "d1-measure", kind: "measure", label: "Prenez la mesure de départ et enregistrez-la" },
      {
        id: "d1-kegel",
        kind: "session",
        label: "Périnée : 3 séries de 10, deux fois aujourd'hui",
        detail:
          "Contractez 5 secondes, relâchez 5 secondes. Le relâchement compte plus que la contraction. Assis, allongé ou debout — personne ne peut voir que vous le faites.",
      },
      { id: "d1-foundation", kind: "foundation", label: "Fondation complète : repas, eau, mouvement, sommeil" },
      { id: "d1-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 2,
    kind: "training",
    phase: "Fondation",
    title: "Première séance",
    focus: "Apprendre l'échelle. S'arrêter à 6.",
    lesson: "the-6-10-method",
    session: {
      title: "Stop-start — séance 1",
      duration: "15 minutes",
      ceiling: "Arrêt à 6 sur 10. Jamais plus haut aujourd'hui.",
      cycles: "3 cycles",
      steps: [
        "Deux minutes de respiration lente avant de commencer. Inspirez par le nez sur quatre temps, expirez par la bouche sur six. Vous abaissez le niveau de départ de votre système nerveux.",
        "Commencez la stimulation à la main. Pas d'écran, pas de téléphone.",
        "À mesure que l'excitation monte, nommez le chiffre pour vous-même. Trois. Quatre. Cinq. Dites-le, même en silence — le nommer est la compétence que vous construisez.",
        "À 6, arrêtez complètement. Mains retirées. Expirez lentement et laissez le périnée se relâcher. Ne serrez pas pour tenir — serrer est le mauvais schéma, et c'est celui qui a aggravé les choses.",
        "Attendez que ça redescende vers 3. Depuis 6, comptez 60 à 90 secondes. Depuis 7, plutôt 2 minutes. Ne regardez pas l'horloge — repartez seulement quand la sensation de traction a complètement disparu.",
        "Trois cycles, puis terminez la séance.",
      ],
      ending: "Terminez sans finir aujourd'hui. Cette première séance porte sur l'échelle, pas sur la libération.",
      guard:
        "Si vous franchissez le point de non-retour par accident, c'est une information, pas un échec — votre 6 était en réalité un 8. Visez plus bas la prochaine fois.",
    },
    brief: [
      "L'entraînement commence aujourd'hui. Cette première séance ne porte pas sur la durée.",
      "Elle porte sur l'apprentissage d'un chiffre.",
      "La plupart des hommes ne sentent pas la différence entre 6 et 10. C'est pour ça que la fin arrive sans prévenir.",
      "Donc : 1 c'est rien. 5 c'est excité et à l'aise. 6 c'est quand ça commence à rouler tout seul. 8 c'est dur. 9 c'est trop tard.",
      "Aujourd'hui vous vivez à 5 et 6. Vous n'approchez jamais 9. Lisez la leçon d'abord — elle est courte.",
    ],
    tasks: [
      { id: "d2-lesson", kind: "lesson", label: "Lire : La méthode 6/10" },
      { id: "d2-session", kind: "session", label: "Séance stop-start 1 — 15 min, 3 cycles, plafond 6" },
      { id: "d2-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d2-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d2-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 3,
    kind: "training",
    phase: "Fondation",
    title: "Deuxième séance",
    focus: "Trouver les signaux qui précèdent le chiffre.",
    lesson: "pelvic-floor",
    session: {
      title: "Stop-start — séance 2",
      duration: "15 à 20 minutes",
      ceiling: "Arrêt à 6 ou 7. Pas 8.",
      cycles: "4 cycles",
      steps: [
        "Deux minutes de respiration d'abord, comme hier.",
        "À la main uniquement. Nommez les chiffres pendant la montée.",
        "Cette séance, remarquez ce que fait votre corps juste avant chaque chiffre. La respiration devient courte. Le périnée se contracte tout seul. Le ventre se rentre. Les orteils se crispent. Chacun a sa signature — trouvez la vôtre.",
        "Arrêtez à 6 ou 7. Relâchez le périnée volontairement, longue expiration.",
        "Laissez redescendre à 3, puis recommencez. Quatre cycles.",
      ],
      ending: "Terminez sans finir.",
      guard:
        "Si votre périnée est douloureux ensuite, c'est que vous serrez pour tenir. Relâchez davantage, contractez moins.",
    },
    brief: [
      "Hier vous avez appris les chiffres. Aujourd'hui vous apprenez les signaux d'alerte.",
      "Juste avant chaque chiffre, votre corps fait quelque chose : la respiration se raccourcit, vous serrez en bas sans le vouloir, le ventre se rentre, les orteils se crispent.",
      "Trouvez les vôtres. Ces signaux arrivent avant le chiffre, et ils vous achètent des secondes.",
      "La leçon du jour traite des kegels correctement. Si vous avez des douleurs en bas, ou si vous êtes tendu en permanence, lisez-la bien — il vous faut l'exercice inverse.",
    ],
    tasks: [
      { id: "d3-lesson", kind: "lesson", label: "Lire : Le périnée — contracter et relâcher" },
      { id: "d3-session", kind: "session", label: "Séance stop-start 2 — 4 cycles, plafond 6-7" },
      { id: "d3-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d3-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d3-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 4,
    kind: "training",
    phase: "Fondation",
    title: "Troisième séance",
    focus: "Tenir à 7 sans serrer.",
    lesson: "breathing",
    session: {
      title: "Stop-start — séance 3",
      duration: "20 minutes",
      ceiling: "7 sur 10.",
      cycles: "4 cycles, avec maintien au sommet",
      steps: [
        "Respiration d'abord. Deux minutes.",
        "Montez à 7, puis au lieu de vous arrêter net, ralentissez fortement et restez à 7 pendant une dizaine de secondes avant d'arrêter complètement.",
        "Pendant ces dix secondes : longue expiration, périnée totalement relâché, épaules basses. Vous vous prouvez qu'une excitation élevée n'oblige pas à perdre le contrôle.",
        "Puis arrêtez, laissez redescendre à 3, recommencez. Quatre cycles.",
      ],
      ending: "Terminez sans finir.",
      guard:
        "Si vous ne pouvez pas rester à 7 sans serrer, c'est que vous êtes à 8. Revenez à un arrêt net à 6 pour cette séance et retentez le maintien au Jour 6.",
    },
    brief: [
      "Aujourd'hui vous ajoutez le maintien.",
      "S'arrêter net vous apprend à fuir. Rester à 7 pendant 10 secondes vous apprend à rester — et c'est ça dont vous avez besoin pendant un rapport.",
      "Vous restez là en vous RELÂCHANT, pas en serrant. Si vous verrouillez pour survivre, vous entraînez la mauvaise chose.",
      "Longue expiration. Tout se relâche. Épaules basses.",
      "Si vous n'y arrivez pas, vous êtes au-dessus de 7. Redescendez à 6.",
    ],
    tasks: [
      { id: "d4-lesson", kind: "lesson", label: "Lire : La respiration et le système nerveux" },
      { id: "d4-session", kind: "session", label: "Séance stop-start 3 — 4 cycles, maintien de 10 s à 7" },
      { id: "d4-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d4-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d4-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 5,
    kind: "rest",
    phase: "Fondation",
    title: "Repos",
    focus: "Pas de séance. Fondation seulement.",
    lesson: "why-pills-fail",
    brief: [
      "Pas de séance aujourd'hui. C'est voulu.",
      "Votre corps construit la compétence les jours de repos, pas les jours d'entraînement. Les hommes qui s'entraînent tous les jours deviennent tendus, s'émoussent et plafonnent en deuxième semaine.",
      "Tout le reste continue : repas, eau, marche, sommeil, kegels, et vos indicateurs ce soir.",
      "Lisez la leçon du jour. Si vous utilisez comprimés, sprays ou alcool, lisez-la deux fois.",
    ],
    tasks: [
      { id: "d5-lesson", kind: "lesson", label: "Lire : Pourquoi les comprimés aggravent les choses" },
      { id: "d5-norest", kind: "rest", label: "Pas de séance stop-start aujourd'hui" },
      { id: "d5-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d5-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d5-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 6,
    kind: "training",
    phase: "Fondation",
    title: "Quatrième séance",
    focus: "Maintiens plus longs. L'échelle devient automatique.",
    lesson: "sleep-and-food",
    session: {
      title: "Stop-start — séance 4",
      duration: "20 minutes",
      ceiling: "7 sur 10.",
      cycles: "4 cycles, maintiens de 20 secondes",
      steps: [
        "Respiration d'abord.",
        "Montez à 7. Maintenez vingt secondes cette fois, fortement ralenti, périnée souple.",
        "Arrêtez, redescendez à 3, recommencez. Quatre cycles.",
        "Au dernier cycle, remarquez le temps qu'il vous faut pour passer de 5 à 7. Comparez au Jour 2 — chez la plupart des hommes c'est déjà plus lent.",
      ],
      ending: "Terminez sans finir.",
    },
    brief: [
      "Mi-parcours. Les maintiens s'allongent aujourd'hui — 20 secondes au lieu de 10.",
      "À ce stade les chiffres devraient arriver tout seuls, sans effort. C'est le but.",
      "Surveillez une chose : le temps qu'il vous faut pour passer de 5 à 7. Comparez au Jour 2. Chez la plupart des hommes c'est déjà plus lent.",
      "C'est votre réflexe qui change. Ça apparaît en général avant le chrono du lit.",
    ],
    tasks: [
      { id: "d6-lesson", kind: "lesson", label: "Lire : Sommeil, alimentation et qualité de l'érection" },
      { id: "d6-session", kind: "session", label: "Séance stop-start 4 — 4 cycles, maintiens de 20 s" },
      { id: "d6-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d6-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d6-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 7,
    kind: "training",
    phase: "Fondation",
    title: "Cinquième séance",
    focus: "Changer la stimulation. Garder le contrôle.",
    lesson: "the-stomach-connection",
    session: {
      title: "Stop-start — séance 5",
      duration: "20 minutes",
      ceiling: "7 sur 10.",
      cycles: "4 cycles, variés",
      steps: [
        "Respiration d'abord.",
        "Cette séance, variez la stimulation entre les cycles — changez de prise, de rythme, de pression. Un contrôle qui ne fonctionne qu'avec une seule technique précise n'est pas un contrôle.",
        "Montez à 7, maintenez vingt secondes, arrêtez, redescendez à 3, recommencez.",
        "Quatre cycles.",
      ],
      ending: "Terminez sans finir.",
      guard:
        "Varier la stimulation rendra l'exercice plus dur. C'est le but. Redescendez votre plafond à 6 si nécessaire.",
    },
    brief: [
      "Un contrôle qui ne marche que d'une seule façon n'est pas un contrôle.",
      "Alors aujourd'hui vous changez exprès — prise différente, rythme différent, pression différente entre les cycles.",
      "Ce sera plus dur qu'hier. Vous devrez peut-être redescendre à 6. Ce n'est pas un recul.",
      "La leçon du jour parle de votre estomac. Sujet bizarre, mais chez certains hommes c'est tout le problème.",
    ],
    tasks: [
      { id: "d7-lesson", kind: "lesson", label: "Lire : Le lien avec l'estomac" },
      { id: "d7-session", kind: "session", label: "Séance stop-start 5 — 4 cycles, stimulation variée" },
      { id: "d7-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d7-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d7-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 8,
    kind: "training",
    phase: "Fondation",
    title: "Sixième séance et point d'étape",
    focus: "Regardez vos indicateurs. Quelque chose a généralement bougé.",
    session: {
      title: "Stop-start — séance 6",
      duration: "20 minutes",
      ceiling: "7, et un cycle à 8 si c'est réellement maîtrisé.",
      cycles: "5 cycles",
      steps: [
        "Respiration d'abord.",
        "Quatre cycles comme au Jour 7 — montée à 7, maintien vingt secondes, arrêt, redescente à 3.",
        "Au cinquième cycle uniquement, et seulement si 7 est réellement confortable, autorisez-vous à toucher 8 puis redescendez immédiatement.",
        "Si 8 ressemble à une lutte, n'y allez pas. Restez à 7. Il n'y a aucune prime à se précipiter.",
      ],
      ending: "Terminez sans finir.",
    },
    brief: [
      "Avant de vous entraîner aujourd'hui, ouvrez Progrès et regardez vos indicateurs.",
      "Le chrono est en général la DERNIÈRE chose à bouger. Énergie, sommeil, érections du matin, et le contrôle que vous ressentez — ça bouge en premier, souvent dès le jour 6 ou 7.",
      "Si ces lignes montent, ça marche. Continuez.",
      "Si absolument rien n'a bougé, écrivez-nous. C'est en général une de trois choses : vous sautez les repas et le sommeil, vous vous entraînez trop haut, ou il y a un souci physique pour un médecin.",
    ],
    tasks: [
      { id: "d8-review", kind: "measure", label: "Ouvrez Progrès et regardez vos indicateurs depuis le Jour 1" },
      { id: "d8-session", kind: "session", label: "Séance stop-start 6 — 5 cycles" },
      { id: "d8-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d8-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d8-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 9,
    kind: "rest",
    phase: "Fondation",
    title: "Repos",
    focus: "Pas de séance. Laissez consolider.",
    lesson: "not-a-habit",
    brief: [
      "Deuxième jour de repos. Pas de séance.",
      "Repas, eau, marche, sommeil, kegels et indicateurs continuent normalement.",
      "Lisez la leçon du jour. Elle est courte. Elle explique comment éviter que cet exercice devienne une habitude.",
    ],
    tasks: [
      { id: "d9-lesson", kind: "lesson", label: "Lire : Un exercice, pas une habitude" },
      { id: "d9-norest", kind: "rest", label: "Pas de séance stop-start aujourd'hui" },
      { id: "d9-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d9-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d9-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 10,
    kind: "training",
    phase: "Fondation",
    title: "Dernière séance",
    focus: "Finir à vos conditions, délibérément.",
    session: {
      title: "Stop-start — séance 7, la dernière du sprint",
      duration: "20 minutes",
      ceiling: "7, puis une fin délibérée.",
      cycles: "4 cycles, puis vous choisissez le moment",
      steps: [
        "Respiration d'abord.",
        "Quatre cycles complets — montée à 7, maintien, arrêt, redescente à 3.",
        "Après le quatrième cycle, finissez délibérément. Pas par accident, pas en perdant le contrôle — vous décidez du moment puis vous y allez.",
        "C'est la moitié de la compétence que vous utiliserez réellement avec une partenaire : non pas éviter la fin indéfiniment, mais choisir quand elle arrive.",
      ],
      ending: "Finissez, délibérément et à votre rythme.",
      guard:
        "C'est votre dernière éjaculation avant la nouvelle mesure. La fenêtre de 48 h commence à cet instant.",
    },
    brief: [
      "Dernière séance du sprint. Celle-ci se termine différemment.",
      "Toutes les séances jusqu'ici finissaient sans jouir. Aujourd'hui vous finissez exprès — vous choisissez le moment, puis vous y allez.",
      "C'est la moitié que vous utiliserez vraiment avec une partenaire. Un homme qui sait seulement éviter n'a rien réglé.",
      "Important : c'est votre DERNIÈRE fois avant le Jour 12. Vos 2 jours nets commencent dès que vous finissez. Rien demain.",
    ],
    tasks: [
      { id: "d10-session", kind: "session", label: "Séance stop-start 7 — 4 cycles, puis une fin délibérée" },
      { id: "d10-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d10-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d10-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 11,
    kind: "rest",
    phase: "Fondation",
    title: "Repos avant la nouvelle mesure",
    focus: "Rien aujourd'hui. Protégez la mesure.",
    brief: [
      "Rien aujourd'hui. Pas de séance, pas de jouissance, pas d'alcool.",
      "Cette journée existe pour garder le chiffre de demain honnête.",
      "Continuez à manger, boire de l'eau et marcher. Dormez bien ce soir — ça seul change le résultat de demain.",
      "Demain : comme au Jour 1. Mêmes 4 points. Ne changez pas la méthode pour embellir le chiffre.",
    ],
    tasks: [
      { id: "d11-nothing", kind: "rest", label: "Pas de séance, pas d'éjaculation, pas d'alcool" },
      { id: "d11-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d11-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d11-sleep", kind: "foundation", label: "Protégez particulièrement le sommeil de ce soir" },
      { id: "d11-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 12,
    kind: "retest",
    phase: "Fondation",
    title: "Nouvelle mesure",
    focus: "Mêmes conditions. Même mode. Obtenez le chiffre.",
    lesson: "reading-your-result",
    brief: [
      "Aujourd'hui vous mesurez à nouveau.",
      "Comme au Jour 1. Mêmes 4 points. Seul ou à deux — ne changez pas.",
      "N'utilisez PAS la technique pendant le test. Pas de stop-and-go. Vous mesurez ce que votre corps fait tout seul maintenant.",
      "DÉMARRER quand vous commencez, STOP quand vous finissez. Puis regardez les deux chiffres.",
      "Lisez la leçon après, quel que soit le résultat. Il y a 4 résultats possibles et 3 sont de bonnes nouvelles.",
    ],
    tasks: [
      { id: "d12-conditions", kind: "measure", label: "Confirmez à nouveau les quatre conditions" },
      { id: "d12-measure", kind: "measure", label: "Prenez la nouvelle mesure et enregistrez-la" },
      { id: "d12-compare", kind: "measure", label: "Comparez vos deux chiffres côte à côte" },
      { id: "d12-lesson", kind: "lesson", label: "Lire : Comment lire votre résultat" },
      { id: "d12-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },

  /* ============ SPRINT DE 30 JOURS — jours 13 à 30 ============ */

  {
    day: 13,
    kind: "review",
    phase: "Trouver le blocage",
    title: "Où vous en êtes vraiment",
    focus: "Identifier ce qui vous limite avant de vous entraîner plus dur.",
    lesson: "finding-the-bottleneck",
    brief: [
      "Seconde moitié. Ce n'est pas juste la même chose en plus long.",
      "Les 12 premiers jours ont construit le contrôle en solo. Les 18 suivants font deux choses de plus : charge plus lourde, et transfert vers le vrai rapport à deux.",
      "Avant ça, aujourd'hui vous cherchez ce qui vous bloque. Regardez vos deux chiffres et vos indicateurs.",
      "Chiffre bougé + indicateurs en hausse ? Il vous faut juste plus de la même chose. Charge dès demain.",
      "Indicateurs en hausse mais chrono à peine bougé ? Votre base se répare, le réflexe suit avec retard. Même route, plus lentement.",
      "Rien n'a bougé du tout ? Stop. Allez faire les analyses ci-dessous avant une séance de plus.",
    ],
    tasks: [
      { id: "d13-review", kind: "measure", label: "Revoyez les deux chiffres et toutes les courbes" },
      { id: "d13-lesson", kind: "lesson", label: "Lire : Trouver votre blocage" },
      {
        id: "d13-labs",
        kind: "medical",
        label: "Si rien n'a bougé : prenez rendez-vous pour un bilan sanguin",
        detail:
          "Tension artérielle, glycémie à jeun ou HbA1c, numération formule sanguine, ferritine, vitamine D, B12, bilan thyroïdien, et testostérone si vos symptômes le justifient. Emportez cette liste.",
      },
      {
        id: "d13-gastric",
        kind: "medical",
        label: "Si votre estomac ne s'est jamais calmé : parlez-en à un médecin",
        detail:
          "Brûlures, reflux ou ballonnements persistants méritent un vrai bilan plutôt qu'un protocole de plus.",
      },
      { id: "d13-foundation", kind: "foundation", label: "La fondation continue" },
      { id: "d13-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 14,
    kind: "training",
    phase: "Trouver le blocage",
    title: "Travail de relâchement",
    focus: "Défaire la tension que douze jours ont pu construire.",
    lesson: "reverse-kegels",
    session: {
      title: "Séance de relâchement",
      duration: "15 minutes",
      ceiling: "Aucun travail d'excitation aujourd'hui.",
      cycles: "Respiration et relâchement uniquement",
      steps: [
        "Allongé sur le dos, genoux pliés, une main sur le ventre.",
        "Respirez dans la main — le ventre monte, la poitrine reste immobile. Dix respirations lentes.",
        "Kegel inversé : à chaque expiration, poussez doucement vers le bas et l'extérieur au lieu de tirer vers le haut. C'est la sensation d'un périnée qui s'allonge, pas qui se resserre. Dix répétitions.",
        "Puis dix cycles de cinq secondes de contraction suivies de quinze secondes de relâchement. Trois fois plus de temps à lâcher qu'à tenir.",
        "Terminez par deux minutes de respiration et rien d'autre.",
      ],
      ending: "Pas d'excitation, pas de fin. C'est de l'entretien.",
    },
    brief: [
      "Pas de travail d'excitation aujourd'hui. Aujourd'hui vous relâchez au lieu de tenir.",
      "Deux semaines de kegels construisent de la force. Ça construit aussi de la tension — et la tension est ce qui fait finir vite beaucoup d'hommes au départ.",
      "Respiration, kegels inversés, longs relâchements. 15 minutes.",
      "Si vous avez eu des douleurs, des crispations, ou une gêne après être resté assis longtemps, c'est la séance la plus utile du programme pour vous. Faites-la tous les 3 jours à partir de maintenant.",
    ],
    tasks: [
      { id: "d14-lesson", kind: "lesson", label: "Lire : Les kegels inversés et le lâcher-prise" },
      { id: "d14-session", kind: "session", label: "Séance de relâchement — 15 minutes" },
      { id: "d14-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d14-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 15,
    kind: "training",
    phase: "Trouver le blocage",
    title: "L'entraînement structuré commence",
    focus: "Ajouter la musculation. La circulation est la variable silencieuse.",
    lesson: "the-training-week",
    session: {
      title: "Stop-start — séance de charge 1",
      duration: "20 minutes",
      ceiling: "7 sur 10.",
      cycles: "5 cycles, maintiens de 30 secondes",
      steps: [
        "Respiration d'abord.",
        "Cinq cycles désormais au lieu de quatre. Montée à 7, maintien trente secondes, arrêt, redescente à 3.",
        "Variez la stimulation entre chaque cycle, comme au Jour 7.",
      ],
      ending: "Terminez sans finir.",
    },
    brief: [
      "Le côté physique devient sérieux aujourd'hui.",
      "Marcher chaque jour était juste pour deux semaines. Pas assez pour un mois.",
      "Nouvelle semaine : 3 séances de renforcement, 2-3 cardio, marche les autres jours, 1 jour de repos.",
      "Le renforcement compte pour une vraie raison — il fait plus pour vos érections en un mois que tout ce qui se vend en flacon.",
      "Pas besoin de salle. Squats, pompes, fentes, gainage, ponts fessiers. 30 minutes, 3 fois par semaine.",
    ],
    tasks: [
      { id: "d15-lesson", kind: "lesson", label: "Lire : Structurer la semaine d'entraînement" },
      { id: "d15-session", kind: "session", label: "Séance de charge 1 — 5 cycles, maintiens de 30 s" },
      { id: "d15-strength", kind: "foundation", label: "Séance de renforcement — 30 minutes" },
      { id: "d15-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d15-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d15-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 16,
    kind: "rest",
    phase: "Trouver le blocage",
    title: "Repos et alimentation structurée",
    focus: "La rotation de repas remplace l'improvisation.",
    lesson: "meal-rotations",
    brief: [
      "Pas de séance d'excitation. Cardio ou longue marche à la place.",
      "Et aujourd'hui vous recevez un vrai plan alimentaire, pas juste « mangez bien ».",
      "Une rotation sur 7 jours pour le petit-déjeuner, le déjeuner et le dîner, avec des aliments que vous pouvez vraiment acheter. Répétez en boucle. Ne réfléchissez pas trop.",
      "C'est dans Leçons pour que vous puissiez l'ouvrir au marché.",
    ],
    tasks: [
      { id: "d16-lesson", kind: "lesson", label: "Lire : La rotation de repas sur sept jours" },
      { id: "d16-norest", kind: "rest", label: "Pas de séance d'excitation aujourd'hui" },
      { id: "d16-cardio", kind: "foundation", label: "Cardio ou longue marche — 40 minutes" },
      { id: "d16-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d16-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d16-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 17,
    kind: "training",
    phase: "Charge",
    title: "Charge — plafond 8",
    focus: "Monter le plafond maintenant que le sol est stable.",
    session: {
      title: "Séance de charge 2",
      duration: "25 minutes",
      ceiling: "8 sur 10 — mais proprement.",
      cycles: "5 cycles, maintiens de 30 secondes",
      steps: [
        "Respiration d'abord.",
        "Montez à 8 au lieu de 7. Maintenez trente secondes à 8, fortement ralenti, périnée totalement souple.",
        "Si vous ne pouvez pas tenir 8 sans serrer, c'est que vous êtes à 9. Restez à 7 toute la séance et retentez au Jour 19.",
        "Cinq cycles.",
      ],
      ending: "Terminez sans finir.",
      guard:
        "8 est le plus haut niveau auquel vous vous entraînerez jamais. 9 est le point de non-retour et on n'y va jamais volontairement.",
    },
    brief: [
      "Le plafond monte aujourd'hui. C'est la seule fois.",
      "8 sur 10 au lieu de 7.",
      "Le test est simple et honnête : si tenir 8 vous fait serrer, vous n'êtes pas à 8, vous êtes à 9. Retournez à 7 pour toute la séance.",
      "Vous ne vous entraînerez JAMAIS au-dessus de 8. 9 c'est trop tard et s'entraîner à paniquer n'est pas une compétence.",
    ],
    tasks: [
      { id: "d17-session", kind: "session", label: "Séance de charge 2 — plafond 8, 5 cycles" },
      { id: "d17-strength", kind: "foundation", label: "Séance de renforcement — 30 minutes" },
      { id: "d17-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d17-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d17-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 18,
    kind: "rest",
    phase: "Charge",
    title: "Relâchement et récupération",
    focus: "Répétez la séance de relâchement.",
    brief: [
      "Pas de travail d'excitation. Refaites la séance de relâchement du Jour 14 en entier.",
      "Tous les 3 jours vous relâchez au lieu de tenir. C'est fixe maintenant.",
      "Les hommes qui sautent ces séances plafonnent en troisième semaine avec un corps qui refuse de se relâcher.",
      "Cardio ou longue marche aussi.",
    ],
    tasks: [
      { id: "d18-session", kind: "session", label: "Séance de relâchement — 15 minutes" },
      { id: "d18-cardio", kind: "foundation", label: "Cardio ou longue marche — 40 minutes" },
      { id: "d18-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d18-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 19,
    kind: "training",
    phase: "Charge",
    title: "Charge — maintiens longs",
    focus: "Soixante secondes au plafond.",
    session: {
      title: "Séance de charge 3",
      duration: "25 minutes",
      ceiling: "8, ou 7 si 8 n'était pas propre au Jour 17.",
      cycles: "4 cycles, maintiens de 60 secondes",
      steps: [
        "Respiration d'abord.",
        "Moins de cycles, maintiens beaucoup plus longs. Montez à votre plafond et restez-y une minute entière.",
        "Ralentissez fortement la stimulation au lieu de l'arrêter. Continuez les longues expirations. Gardez le périnée souple.",
        "Quatre cycles.",
      ],
      ending: "Terminez sans finir.",
    },
    brief: [
      "Moins de cycles, maintiens beaucoup plus longs. Une minute entière à votre plafond.",
      "Et cette fois vous ne vous arrêtez pas — vous ralentissez fortement et vous continuez.",
      "Une minute à votre plafond avec la stimulation qui continue est beaucoup plus proche d'un vrai rapport qu'un arrêt net.",
      "C'est là que ça commence à ressembler à la vraie chose.",
    ],
    tasks: [
      { id: "d19-session", kind: "session", label: "Séance de charge 3 — 4 cycles, maintiens de 60 s" },
      { id: "d19-strength", kind: "foundation", label: "Séance de renforcement — 30 minutes" },
      { id: "d19-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d19-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d19-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 20,
    kind: "training",
    phase: "Charge",
    title: "Charge — sans jamais retirer les mains",
    focus: "Contrôler sans jamais s'arrêter.",
    session: {
      title: "Séance de charge 4",
      duration: "25 minutes",
      ceiling: "7 – 8, en continu.",
      cycles: "Continu, sans arrêt complet",
      steps: [
        "Respiration d'abord.",
        "Cette séance, vous ne retirez jamais les mains. Vous régulez en ralentissant, en changeant la pression et en expirant.",
        "Naviguez entre 5 et 7 aussi longtemps que possible — vingt minutes si vous y arrivez. Laissez monter, faites redescendre, laissez remonter.",
        "Si vous atteignez 8, ralentissez presque jusqu'à l'arrêt mais gardez le contact.",
      ],
      ending: "Terminez sans finir.",
      guard:
        "C'est la séance la plus difficile du programme. Terminer plus tôt n'est pas un échec — notez combien de temps vous avez tenu et battez ce chiffre la prochaine fois.",
    },
    brief: [
      "La séance la plus dure du programme. Et la plus proche d'un vrai rapport.",
      "Vous ne retirez jamais les mains. Vous gérez en ralentissant, en changeant la pression, et en expirant.",
      "Naviguez entre 5 et 7 aussi longtemps que possible. 20 minutes si vous y arrivez.",
      "La plupart des hommes ne tiennent pas les 20 minutes du premier coup. Notez votre temps et battez-le la prochaine fois.",
    ],
    tasks: [
      { id: "d20-session", kind: "session", label: "Séance de charge 4 — continu, sans retirer les mains" },
      { id: "d20-cardio", kind: "foundation", label: "Cardio ou longue marche — 40 minutes" },
      { id: "d20-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d20-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d20-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 21,
    kind: "rest",
    phase: "Charge",
    title: "Relâchement et préparation",
    focus: "Repos, et lecture avant la phase à deux.",
    lesson: "the-conversation",
    brief: [
      "Séance de relâchement et repos du travail d'excitation.",
      "Lisez bien la leçon du jour. La phase qui commence dans deux jours est celle que les hommes ratent le plus — et ce n'est pas la technique, c'est la conversation.",
      "Si vous commencez à faire des pauses et changer de position sans explication, elle comblera le vide toute seule. Ce n'est presque jamais la bonne réponse.",
      "Dix secondes d'honnêteté suppriment tout le problème. La leçon vous donne les mots.",
    ],
    tasks: [
      { id: "d21-lesson", kind: "lesson", label: "Lire : La conversation à avoir d'abord" },
      { id: "d21-session", kind: "session", label: "Séance de relâchement — 15 minutes" },
      { id: "d21-strength", kind: "foundation", label: "Séance de renforcement — 30 minutes" },
      { id: "d21-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d21-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 22,
    kind: "training",
    phase: "Charge",
    title: "Dernière séance solo",
    focus: "Consolider avant le transfert.",
    session: {
      title: "Séance de charge 5",
      duration: "25 minutes",
      ceiling: "8, maîtrisé.",
      cycles: "4 cycles, maintiens de 60 s, stimulation variée",
      steps: [
        "Respiration d'abord.",
        "Quatre cycles à 8, une minute de maintien chacun, en variant la stimulation entre les cycles.",
        "Finissez délibérément au dernier cycle — vous choisissez le moment.",
      ],
      ending: "Fin délibérée, à votre rythme.",
    },
    brief: [
      "Dernière séance solo. À partir d'ici ça passe au vrai rapport, là où c'est sa place.",
      "Finissez celle-ci exprès, comme au Jour 10 — vous choisissez le moment.",
      "Vous allez en avoir besoin sous beaucoup plus de pression dès demain.",
    ],
    tasks: [
      { id: "d22-session", kind: "session", label: "Séance de charge 5 — puis une fin délibérée" },
      { id: "d22-cardio", kind: "foundation", label: "Cardio ou longue marche — 40 minutes" },
      { id: "d22-kegel", kind: "session", label: "Périnée : 3 séries de 10, deux fois" },
      { id: "d22-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d22-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 23,
    kind: "training",
    phase: "Transfert",
    title: "Phase à deux — lire l'échelle ensemble",
    focus: "La même échelle, avec quelqu'un d'autre dans la pièce.",
    lesson: "partner-stop-start",
    session: {
      title: "Séance à deux 1 — sans pénétration",
      duration: "Le temps qu'il faudra",
      ceiling: "6 sur 10.",
      cycles: "3 cycles",
      steps: [
        "Ayez la conversation d'abord. Ne la sautez pas et ne l'improvisez pas.",
        "Pas de pénétration ce soir. Stimulation manuelle par votre partenaire uniquement.",
        "Même échelle, mêmes règles — nommez le chiffre pour vous-même, arrêtez à 6, relâchez le périnée, expirez.",
        "Trois cycles, puis arrêtez. Vous pouvez finir ou non, à votre choix.",
      ],
      ending: "À votre choix.",
      guard:
        "Si vous n'avez pas de partenaire actuellement, répétez la séance continue du Jour 20 et revenez à cette phase quand ce sera le cas. Rien n'est perdu.",
    },
    brief: [
      "C'est la phase qui sépare les hommes qui progressent seuls des hommes qui progressent là où ça compte.",
      "Le contrôle en solo ne se transfère PAS tout seul. Une partenaire ajoute de la surprise, de la pression et plus d'excitation.",
      "Des hommes qui tiennent 7 facilement seuls atteignent 9 en 90 secondes dès qu'on les touche. C'est normal. C'est une version plus dure de la même compétence.",
      "Donc on reconstruit depuis le bas. Ce soir : aucune pénétration. Les mains seulement. Plafond de 6. Trois cycles.",
      "Ayez la conversation AVANT de commencer. Ne sautez pas cette étape.",
    ],
    tasks: [
      { id: "d23-lesson", kind: "lesson", label: "Lire : Le stop-start avec partenaire" },
      { id: "d23-talk", kind: "partner", label: "Ayez la conversation avant de commencer" },
      { id: "d23-session", kind: "partner", label: "Séance à deux 1 — manuelle uniquement, plafond 6" },
      { id: "d23-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d23-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 24,
    kind: "rest",
    phase: "Transfert",
    title: "Repos et relâchement",
    focus: "Récupérer entre les séances à deux.",
    brief: [
      "Pas de travail d'excitation. Séance de relâchement, cardio, repas, sommeil.",
      "Les séances à deux prennent plus d'énergie que les séances solo. Un jour sur deux pendant cette phase.",
    ],
    tasks: [
      { id: "d24-session", kind: "session", label: "Séance de relâchement — 15 minutes" },
      { id: "d24-cardio", kind: "foundation", label: "Cardio ou longue marche — 40 minutes" },
      { id: "d24-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d24-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 25,
    kind: "training",
    phase: "Transfert",
    title: "Phase à deux — entrer et faire une pause",
    focus: "Pénétration, puis immobilité.",
    lesson: "pause-and-stay",
    session: {
      title: "Séance à deux 2 — entrer et tenir",
      duration: "Le temps qu'il faudra",
      ceiling: "6 – 7.",
      cycles: "3 entrées",
      steps: [
        "Préliminaires normaux. Ne vous précipitez pas vers la pénétration.",
        "Entrez, puis restez complètement immobile. Aucun mouvement pendant trente secondes. Longue expiration. Laissez le périnée se relâcher.",
        "L'entrée est le moment de plus forte excitation pour la plupart des hommes qui finissent vite, et l'immobilité est la façon d'y survivre sans se retirer.",
        "Si vous atteignez 7, restez immobile plus longtemps. Si vous atteignez 8, retirez-vous, attendez, et entrez à nouveau.",
        "Trois entrées, puis bougez normalement si vous êtes à l'aise.",
      ],
      ending: "À votre choix.",
    },
    brief: [
      "La pénétration est le moment où la plupart des hommes perdent pied. Le saut de 5 à 9 se fait en secondes.",
      "Alors ce soir vous séparez la pénétration du mouvement.",
      "Entrez, puis arrêtez net. Aucun mouvement pendant 30 secondes. Longue expiration. Tout se relâche.",
      "La plupart des hommes trouvent les 10 premières secondes dures et les 20 suivantes étonnamment faciles.",
      "Trois fois. Puis bougez normalement si vous êtes à l'aise.",
    ],
    tasks: [
      { id: "d25-lesson", kind: "lesson", label: "Lire : Pause et reste à l'intérieur" },
      { id: "d25-session", kind: "partner", label: "Séance à deux 2 — entrer et rester immobile" },
      { id: "d25-strength", kind: "foundation", label: "Séance de renforcement — 30 minutes" },
      { id: "d25-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d25-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 26,
    kind: "rest",
    phase: "Transfert",
    title: "Repos et relâchement",
    focus: "Récupérer.",
    brief: [
      "Séance de relâchement, cardio, fondation. Pas de travail d'excitation.",
    ],
    tasks: [
      { id: "d26-session", kind: "session", label: "Séance de relâchement — 15 minutes" },
      { id: "d26-cardio", kind: "foundation", label: "Cardio ou longue marche — 40 minutes" },
      { id: "d26-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d26-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 27,
    kind: "training",
    phase: "Transfert",
    title: "Phase à deux — mouvement et position",
    focus: "Ajouter le mouvement. Utiliser la position comme réglage.",
    lesson: "positions",
    session: {
      title: "Séance à deux 3 — mouvement contrôlé",
      duration: "Le temps qu'il faudra",
      ceiling: "7.",
      cycles: "Continu, avec pauses si nécessaire",
      steps: [
        "Entrez et restez immobile trente secondes, comme au Jour 25.",
        "Commencez à bouger lentement. Peu profond plutôt que profond. Nommez votre chiffre au fur et à mesure.",
        "À 7, arrêtez de bouger et restez à l'intérieur. Trente secondes d'immobilité, longue expiration, périnée souple. Puis reprenez.",
        "Utilisez la position délibérément : les positions où elle est au-dessus ou où vous êtes sur le côté donnent bien moins de stimulation que vous à genoux. Changez de position comme réglage, pas comme sauvetage.",
      ],
      ending: "À votre choix.",
    },
    brief: [
      "Le mouvement entre aujourd'hui, plus le dernier outil : la position.",
      "Les positions donnent des quantités de stimulation très différentes. Elle au-dessus vous en donne bien moins que vous au-dessus. Sur le côté, encore moins. Peu profond, beaucoup moins que profond.",
      "La position est donc un bouton. Tournez-le TÔT, avant d'en avoir besoin.",
      "Les hommes qui réussissent changent de position à 6, par habitude. Ceux qui galèrent changent à 9, pour sauver. À ce moment-là c'est joué.",
    ],
    tasks: [
      { id: "d27-lesson", kind: "lesson", label: "Lire : La position comme réglage" },
      { id: "d27-session", kind: "partner", label: "Séance à deux 3 — mouvement avec pauses" },
      { id: "d27-strength", kind: "foundation", label: "Séance de renforcement — 30 minutes" },
      { id: "d27-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d27-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 28,
    kind: "rest",
    phase: "Transfert",
    title: "Repos avant la mesure finale",
    focus: "Plus d'éjaculation à partir de ce soir. La fenêtre s'ouvre.",
    brief: [
      "Séance de relâchement et fondation. Pas de travail d'excitation.",
      "À partir de ce soir, plus de jouissance. Vos 2 jours nets pour la mesure finale commencent maintenant.",
      "Comme au Jour 11 : protégez votre sommeil, pas d'alcool, ne changez pas la méthode.",
    ],
    tasks: [
      { id: "d28-session", kind: "session", label: "Séance de relâchement — 15 minutes" },
      { id: "d28-window", kind: "rest", label: "Pas d'éjaculation — la fenêtre de 48 h commence" },
      { id: "d28-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d28-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 29,
    kind: "rest",
    phase: "Consolidation",
    title: "Repos",
    focus: "Protégez la mesure de demain.",
    brief: [
      "Rien aujourd'hui. Pas de séance, pas de jouissance, pas d'alcool.",
      "Dormez bien. Demain c'est votre chiffre final, de la même façon qu'au Jour 1 et au Jour 12.",
    ],
    tasks: [
      { id: "d29-nothing", kind: "rest", label: "Pas de séance, pas d'éjaculation, pas d'alcool" },
      { id: "d29-foundation", kind: "foundation", label: "Fondation complète" },
      { id: "d29-sleep", kind: "foundation", label: "Protégez le sommeil de ce soir" },
      { id: "d29-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
  {
    day: 30,
    kind: "retest",
    phase: "Consolidation",
    title: "Mesure finale et la suite",
    focus: "Trois chiffres. Puis un plan tenable.",
    lesson: "maintenance",
    brief: [
      "Mesure finale. Mêmes 4 points, même façon que depuis le Jour 1.",
      "Puis regardez les trois chiffres ensemble — Jour 1, Jour 12, Jour 30 — à côté de 30 jours d'indicateurs.",
      "C'est le récit honnête de ce qui s'est passé, et il vous appartient.",
      "La dernière leçon parle de garder les acquis. Ce que vous avez construit s'efface si vous arrêtez — pas du jour au lendemain, mais en quelques mois.",
      "L'entretien est léger exprès : 2 séances par semaine, kegels 3 fois par semaine, les repas et le sommeil, et une mesure par mois.",
      "Et mettez l'exercice solo à la retraite. C'était un échafaudage. Si vous le préférez au rapport, arrêtez et écrivez-nous.",
    ],
    tasks: [
      { id: "d30-conditions", kind: "measure", label: "Confirmez les quatre conditions du test" },
      { id: "d30-measure", kind: "measure", label: "Prenez la mesure finale et enregistrez-la" },
      { id: "d30-review", kind: "measure", label: "Revoyez les trois chiffres et vos courbes" },
      { id: "d30-lesson", kind: "lesson", label: "Lire : L'entretien — conserver ce que vous avez construit" },
      { id: "d30-log", kind: "measure", label: "Notez les indicateurs du soir" },
    ],
  },
];

export const protocolFr: Protocol = { rules, rulesIntro, days };
