"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { getPrices, type Plan } from "@/lib/payments";
import { getDirect } from "@/lib/content/direct";
import { getMarketing } from "@/lib/content/marketing";
import { track } from "@/lib/track";
import { update } from "@/lib/store";
import { Countdown, useOfferExpired } from "@/components/c/Countdown";
import { Quiz3 } from "@/components/c/Quiz3";
import { MetaPixel } from "@/components/MetaPixel";
import { Logo } from "@/components/Logo";

type Copy = { quiz: { q: string; options: string[] }[]; l: Record<string, string> };
const EN: Copy = {
  quiz: [
    { q: "Do you often finish sooner than you'd like during sex?", options: ["Yes", "Sometimes", "No"] },
    { q: "Would you like better control without relying on pills, herbs, or supplements?", options: ["Yes", "No"] },
    { q: "Can you commit about 15 minutes a day for the next 10 days?", options: ["Yes", "No"] },
  ],
  l: { tagline: "LONGER LASTING SEX", cta: "START 10-DAY CHALLENGE", timer: "SPECIAL OFFER ENDS IN", heroA: "CAN YOU TRAIN YOURSELF", heroB: "TO LAST LONGER", heroC: "AND CONSISTENTLY?", heroSub: "Answer 3 quick questions and we'll tell you if this program is right for you.", question: "QUESTION {n} OF {total}", next: "NEXT QUESTION", private: "Your answers are 100% private.", goodKicker: "BASED ON YOUR ANSWERS", goodA: "YOU'RE A", goodB: "GOOD FIT", goodSub: "You don't need pills or complicated routines.", gymA: "METRON IS LIKE A GYM", gymB: "FOR YOUR SEXUAL PERFORMANCE.", gymBody: "But no heavy lifting. No two-hour sessions. No forever. Just a simple, private plan you can follow in about 15 minutes a day.", trainingKicker: "HOW METRON WORKS", trainingA: "REAL TRAINING", trainingB: "FOR REAL RESULTS.", trainingSub: "You don't build physical control by wishing for it. You train it.", planKicker: "THE 10-DAY CHALLENGE", planA: "A SIMPLE PLAN.", planB: "REAL RESULTS.", planSub: "Start with 10 days. Measure the difference yourself.", diffKicker: "THE DIFFERENCE", diffA: "SAME YOU.", diffB: "A BETTER EXPERIENCE.", proofKicker: "PROOF", proofA: "PRIVATE. SIMPLE.", proofB: "REAL RESULTS.", costKicker: "THE COST OF", costA: "NOT STARTING", costB: "IS HIGHER THAN YOU THINK.", getA: "10 DAYS TO A", getB: "LONGER LASTING YOU", getC: "AND A HAPPIER SEX LIFE.", closeA: "READY FOR", closeB: "YOUR RESULTS?", closeSub: "Your 10-day challenge is reserved at {price} for the next 7 hours.", nextKicker: "AFTER YOUR 10 DAYS", nextA: "THEN THERE IS", nextB: "THE 30-DAY PROGRAM.", nextSub: "The 10 days show you your number can move. The 30 days make it hold, and take it out of your own hands and into real sex.", next1: "Everything in the 10-day challenge, continued and loaded heavier", next2: "The partner phase — control on your own and control with her are two different skills", next3: "What to say to her, so it never feels like a clinic", next4: "Food, sleep and strength work that support the rest", nextNote: "You do not decide that today. Take the 10-day challenge, measure on day 10, and see the difference for yourself first. The 30-day program is there when you have earned the right to want it." },
};
const FR: Copy = { quiz: [{ q: "Finissez-vous souvent plus tôt que vous ne le voudriez pendant les rapports ?", options: ["Oui", "Parfois", "Non"] }, { q: "Voulez-vous un meilleur contrôle sans dépendre de pilules, de plantes ou de compléments ?", options: ["Oui", "Non"] }, { q: "Pouvez-vous consacrer environ 15 minutes par jour pendant les 10 prochains jours ?", options: ["Oui", "Non"] }], l: { ...EN.l, tagline: "DU SEXE QUI DURE PLUS LONGTEMPS", cta: "COMMENCER LE DÉFI 10 JOURS", timer: "OFFRE SPÉCIALE SE TERMINE DANS", heroA: "POUVEZ-VOUS VOUS ENTRAÎNER", heroB: "À TENIR PLUS LONGTEMPS", heroC: "ET DE FAÇON CONSTANTE ?", heroSub: "Répondez à 3 questions rapides et nous vous dirons si ce programme est fait pour vous.", question: "QUESTION {n} SUR {total}", next: "QUESTION SUIVANTE", private: "Vos réponses sont 100% privées.", goodKicker: "D'APRÈS VOS RÉPONSES", goodA: "VOUS ÊTES", goodB: "UN BON PROFIL", goodSub: "Vous n'avez besoin ni de pilules ni de routines compliquées.", gymA: "METRON, C'EST COMME UNE SALLE", gymB: "POUR VOTRE PERFORMANCE SEXUELLE.", gymBody: "Pas de charges lourdes. Pas de séances de deux heures. Juste un plan privé et simple, environ 15 minutes par jour.", trainingKicker: "COMMENT METRON FONCTIONNE", trainingA: "UN VRAI ENTRAÎNEMENT", trainingB: "POUR DE VRAIS RÉSULTATS.", trainingSub: "On ne construit pas le contrôle physique en le souhaitant. On l'entraîne.", planKicker: "LE DÉFI DE 10 JOURS", planA: "UN PLAN SIMPLE.", planB: "DE VRAIS RÉSULTATS.", planSub: "Commencez par 10 jours. Mesurez vous-même la différence.", diffKicker: "LA DIFFÉRENCE", diffA: "LE MÊME VOUS.", diffB: "UNE MEILLEURE EXPÉRIENCE.", proofKicker: "LA PREUVE", proofA: "PRIVÉ. SIMPLE.", proofB: "DE VRAIS RÉSULTATS.", costKicker: "LE COÛT DE", costA: "NE PAS COMMENCER", costB: "EST PLUS ÉLEVÉ QUE VOUS NE PENSEZ.", getA: "10 JOURS POUR", getB: "TENIR PLUS LONGTEMPS", getC: "ET UNE VIE SEXUELLE PLUS HEUREUSE.", closeA: "PRÊT POUR", closeB: "VOS RÉSULTATS ?", closeSub: "Votre défi de 10 jours est réservé à {price} pour les 7 prochaines heures.", nextKicker: "APRÈS VOS 10 JOURS", nextA: "ENSUITE, IL Y A", nextB: "LE PROGRAMME DE 30 JOURS.", nextSub: "Les 10 jours vous montrent que votre chiffre peut bouger. Les 30 jours le consolident, et le font sortir de vos propres mains pour aller dans de vrais rapports.", next1: "Tout ce qu'il y a dans le défi de 10 jours, poursuivi et intensifié", next2: "La phase avec partenaire — se contrôler seul et se contrôler avec elle sont deux compétences différentes", next3: "Quoi lui dire, pour que ça ne ressemble jamais à une consultation", next4: "Alimentation, sommeil et travail de force pour soutenir le reste", nextNote: "Vous ne décidez pas ça aujourd'hui. Faites le défi de 10 jours, mesurez au jour 10, et voyez la différence par vous-même d'abord. Le programme de 30 jours sera là quand vous aurez gagné le droit de le vouloir." } };

type IconName = "lock" | "leaf" | "clock" | "chart" | "check" | "cross" | "phone" | "heart" | "eye" | "bolt";
function Icon({ name, className = "h-5 w-5" }: { name: IconName; className?: string }) { const d: Record<IconName, string> = { lock: "M7 10V7a5 5 0 0 1 10 0v3M5.5 10h13v10h-13z", leaf: "M5 19c0-7 5-12 14-13 0 9-5 14-12 14H5v-1Zm2 0 8-8", clock: "M12 7v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z", chart: "M5 19V10m5 9V5m5 14v-7m5 7V8", check: "M4 12.5 9 17.5 20 6.5", cross: "M6 6l12 12M18 6 6 18", phone: "M8 3h8a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Zm3 15h2", heart: "M12 20s-7-4.4-7-9.3A4 4 0 0 1 12 8a4 4 0 0 1 7 2.7C19 15.6 12 20 12 20Z", eye: "M2 12s3.5-6 10-6 10 6-3.5 6-10 6-10-6-10-6Zm10 2.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z", bolt: "M13 2 5 13h6l-1 9 8-11h-6l1-9Z" }; return <svg viewBox="0 0 24 24" fill="none" className={className} aria-hidden><path d={d[name]} stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>; }

export function ChallengeClient({ locale, geoCountry }: { locale: string; geoCountry?: string | null }) {
  const { quiz, l } = locale === "fr" ? FR : EN; const [passed, setPassed] = useState(false); const reveal = useRef<HTMLDivElement>(null);
  /* The clock has to be worth something. While it runs he sees the offer
     price; when it runs out the page shows what the plan was listed at
     before, and stays there for him. `was` comes from the price book, so the
     number is one this plan genuinely carried rather than one invented to
     make the discount look bigger. */
  const testRow = getPrices(geoCountry ?? "default").find((p) => p.plan === ("test" as Plan));
  const expired = useOfferExpired();
  const price = (expired ? testRow?.was : testRow?.display) ?? testRow?.display ?? "2 500 FCFA"; const direct = getDirect(locale); const marketing = getMarketing(locale);
  useEffect(() => { try { const p = new URLSearchParams(window.location.search); const campaign = (p.get("c") ?? p.get("utm_campaign") ?? "").replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 40); if (campaign) update((s) => s.campaign ? s : { ...s, campaign }, locale); } catch {} track("start_view", "c", locale); }, [locale]);
  const complete = useCallback(() => { setPassed(true); track("quiz_complete", "c", locale); window.setTimeout(() => reveal.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 80); }, [locale]);
  const Go = ({ where, className = "" }: { where: string; className?: string }) => <Link href={`/${locale}/offer`} onClick={() => track("start_cta", `c_${where}`, locale)} className={`btn-lime c-cta ${className}`}>{l.cta}</Link>;
  const Heading = ({ kicker, a, b, c }: { kicker?: string; a: string; b: string; c?: string }) => <>{kicker && <p className="c-kicker">{kicker}</p>}<h2 className="c-heading">{a}<br /><span>{b}</span>{c && <><br />{c}</>}</h2></>;
  const Trust = () => <div className="c-trust">{[["lock", "100% Private", "No one has to know."], ["leaf", "No pills. No herbs.", "Just training."], ["phone", "Works on any device", "Train from your phone."]].map(([icon, title, body]) => <div key={title} className="c-trust-item"><Icon name={icon as IconName} /><p><strong>{title}</strong><small>{body}</small></p></div>)}</div>;
  const pillars = [["01", "Awareness", "Measure how long you last on day 1, so you know your starting point."], ["02", "Breathing", "How you breathe has a direct impact on your stamina and control."], ["03", "Pelvic-floor control", "Build control over the muscles that can make you finish sooner than you wanted."], ["04", "Arousal management", "Learn to recognise when you are close, then train your body to stay in control for longer."], ["05", "Practical exercises", "Simple exercises combining it all — no more than 15 minutes a day."], ["06", "Progress tracking", "Track every training day and measure again at the end to see the difference."]];
  return <><style>{`body{background:#030303;color:#fff}body::before{display:none}`}</style><MetaPixel event="ViewContent" /><div className="c-page"><header className="c-bar"><div className="c-bar-inner"><span className="c-brand"><Logo size="sm" /><small>{l.tagline}</small></span><div className="c-bar-timer"><Countdown label={l.timer} hrs="HRS" mins="MINS" secs="SECS" compact /></div><Go where="bar" /></div></header><main className="c-shell">
    <section className="c-hero c-photo"><Image src="/c/hero-editorial.png" fill priority sizes="(max-width: 768px) 100vw, 1100px" alt="" className="c-photo-image" /><div className="c-photo-shade" /><div className="c-hero-copy"><h1 className="c-heading">{l.heroA}<br /><span>{l.heroB}</span><br />{l.heroC}</h1><i className="c-rule" /><p className="c-lede">{l.heroSub}</p><div className="c-benefits">{[["lock", "Private.", "No one has to know."], ["leaf", "No pills.", "No herbs."], ["clock", "Just 15 minutes", "a day."], ["chart", "Real results.", "Naturally."]].map(([icon, title, sub]) => <div key={title}><b><Icon name={icon as IconName} /></b><strong>{title}</strong><small>{sub}</small></div>)}</div><p className="c-script">A Better You in Bed</p></div></section>
    <section className="c-quiz"><Quiz3 quals={quiz} ofLabel={l.question} privateNote={l.private} onDone={complete} /></section>
    <div ref={reveal} className={passed ? "c-reveal" : "hidden"} aria-hidden={!passed}>
      <section className="c-good c-photo"><Image src="/c/fit-clean.jpg" fill sizes="(max-width: 768px) 100vw, 1100px" alt="" className="c-photo-image" /><div className="c-photo-shade" /><div className="c-panel-copy"><Heading kicker={l.goodKicker} a={l.goodA} b={l.goodB} /><p className="c-lede">{l.goodSub}</p><div className="c-gym"><h3>{l.gymA}<br /><span>{l.gymB}</span></h3><p>{l.gymBody}</p></div><Go where="good-fit" /></div></section>
      <section className="c-section c-training"><div className="c-section-copy"><Heading kicker={l.trainingKicker} a={l.trainingA} b={l.trainingB} /><p className="c-lede">{l.trainingSub}</p></div><Image src="/c/training-clean.jpg" width={419} height={420} alt="" className="c-section-photo" /><div className="c-pillar-grid">{pillars.map(([n, title, body]) => <article key={n} className="c-pillar"><b>{n}</b><h3>{title}</h3><p>{body}</p></article>)}</div><div className="c-bonus"><b>DAY 10<br /><span>BONUS</span></b><p><strong>How to make her come first</strong><small>Know her arousal point for a more satisfying experience for both of you.</small></p></div><Go where="training" className="c-center" /></section>
      <section className="c-plan c-photo"><Image src="/c/plan-clean.jpg" fill sizes="(max-width: 768px) 100vw, 1100px" alt="" className="c-photo-image" /><div className="c-photo-shade" /><div className="c-panel-copy"><Heading kicker={l.planKicker} a={l.planA} b={l.planB} /><p className="c-lede">{l.planSub}</p><div className="c-timeline">{[["DAY 1", "Complete your baseline measurement."], ["DAYS 2–9", "Follow your daily training."], ["DAY 10", "Repeat the measurement. See what changed."]].map(([day, body], i) => <div key={day}><b>{day}</b><i>{i < 2 ? "↓" : "✓"}</i><p>{body}</p></div>)}</div></div></section>
      <section className="c-section c-difference"><Heading kicker={l.diffKicker} a={l.diffA} b={l.diffB} /><p className="c-lede">It’s not about being someone else. It’s about getting better at what matters.</p><div className="c-compare"><article className="c-without"><h3>WITHOUT METRON</h3>{["Guessing what to do", "Inconsistent control", "Frustration", "Relying on quick fixes", "Wondering if things will improve"].map((x) => <p key={x}><Icon name="cross" />{x}</p>)}</article><article className="c-with"><h3>WITH METRON</h3>{["A structured daily routine", "Practical control techniques", "Better awareness", "Increased confidence", "Measurable progress"].map((x) => <p key={x}><Icon name="check" />{x}</p>)}</article></div><Trust /><Go where="difference" className="c-center" /></section>
      <section className="c-proof c-photo"><Image src="/c/proof-clean.jpg" fill sizes="(max-width: 768px) 100vw, 1100px" alt="" className="c-photo-image" /><div className="c-photo-shade" /><div className="c-panel-copy"><Heading kicker={l.proofKicker} a={l.proofA} b={l.proofB} /><p className="c-lede">Private. Simple. No pills. No herbs. 15 minutes a day. No one has to know.</p><div className="c-proof-points"><span><Icon name="heart" />Last longer</span><span><Icon name="chart" />More confidence</span><span><Icon name="check" />Measurable progress</span></div></div></section>
      {(direct.testimonials.length > 0 || direct.shots.length > 0) && <section className="c-section c-reviews"><h2 className="c-review-title">REAL MEN. <span>REAL RESULTS.</span></h2>{direct.testimonials.length > 0 && <div className="c-review-grid">{direct.testimonials.map((t) => <figure key={t.quote}><blockquote>“{t.quote}”</blockquote><figcaption>{t.who}</figcaption></figure>)}</div>}{direct.shots.length > 0 && <div className="c-shot-grid">{direct.shots.map((s) => <figure key={s.src}><Image src={s.src} width={700} height={900} alt={s.alt} /><figcaption>{s.caption}</figcaption></figure>)}</div>}</section>}
      <section className="c-cost c-photo"><Image src="/c/cost-clean.jpg" fill sizes="(max-width: 768px) 100vw, 1100px" alt="" className="c-photo-image" /><div className="c-photo-shade" /><div className="c-panel-copy"><Heading kicker={l.costKicker} a={l.costA} b={l.costB} /><p className="c-lede">The longer you stay at a particular duration, the harder it becomes to change it.</p><p className="c-cost-copy">If you’re unhappy with your sexual performance, waiting another month doesn’t make you last longer. <strong>Training does.</strong> {price} shouldn’t be the reason you spend another month unhappy with your sex life.</p><Go where="cost" /></div></section>
      <section className="c-get c-photo"><Image src="/c/final-clean.jpg" fill sizes="(max-width: 768px) 100vw, 1100px" alt="" className="c-photo-image" /><div className="c-photo-shade" /><div className="c-panel-copy"><Heading a={l.getA} b={l.getB} c={l.getC} /><div className="c-includes">{[["bolt", "Daily lessons"], ["eye", "Practical guides"], ["chart", "Progress tracker"], ["heart", "Lifetime access"]].map(([icon, text]) => <span key={text}><Icon name={icon as IconName} />{text}</span>)}</div></div></section>
      {/* ── WHAT COMES AFTER ──────────────────────────────────────────
          The 30-day programme, placed last and deliberately not for sale
          here. Two prices on one page splits the decision and loses both;
          and a man who has not measured anything yet has no reason to
          believe the bigger one. He is told it exists, told what it adds,
          and told to earn it with ten days first. */}
      <section className="c-section c-next">
        <p className="c-kicker">{l.nextKicker}</p>
        <h2 className="c-heading">{l.nextA}<br /><span>{l.nextB}</span></h2>
        <p className="c-lede">{l.nextSub}</p>
        <div className="c-next-grid">
          {[l.next1, l.next2, l.next3, l.next4].map((x) => (
            <p key={x}><Icon name="check" />{x}</p>
          ))}
        </div>
        <p className="c-next-note">{l.nextNote}</p>
      </section>
      <section className="c-close"><div><Heading a={l.closeA} b={l.closeB} /><p className="c-lede">{l.closeSub.replace("{price}", price)}</p><p className="c-close-note">You can either keep wondering if you can improve — or spend the next 10 days finding out.</p></div><Countdown label={l.timer} hrs="HRS" mins="MINS" secs="SECS" /><Go where="close" className="c-full" /><Trust /></section><footer className="c-footer">{marketing.disclaimer}</footer>
    </div></main><div className="c-mobile-buy"><Countdown label={l.timer} hrs="HRS" mins="MINS" secs="SECS" compact /><Go where="mobile" /></div></div></>;
}
